### ISSUE TITLE
Chat and Notification APIs

### ISSUE THREAD

**Issue by billypilgrim88** [CarSnoop-Inc/carsnoop-issues#1]

**Comment by jongilman8** [comment]
I have finished the setup described above. The next step is creating REST APIs that:

1. Send a message and associate it to a connectionId
2. Retrieve all messages associated with a connectionId

Ideally the connectionId would be either the transaction ID in our database if the conversation is between buyer and seller, or account ID if the conversation is between CarSnoop support and a user.

**Comment by reutenkoivan** [comment]
> The next step is creating REST APIs

Do we need to use the "Long polling" technique for updating the list of messages? Or just infinitely request them in every determined period of time?
