### ISSUE TITLE
updateVehicles - new API to check for new vehicles daily

### ISSUE THREAD

**Issue by billypilgrim88** [CarSnoop-Inc/carsnoop-issues#10]

**Comment by jongilman8** [comment]
1. Job 1 (Weekly) - call synchronizeVehicleData and synchronizeVehicleDataCPI for current year and CY+1 and load any new vehicles into the vehicles table
2. Job 2 (Daily) - readVehicleDetails retrieves colors and standard equipment for a specific UVC - unique vehicle code. Check DB for any vehilces in the vehicles table where colors or equipment are NULL, then call API to get those details and update DB. Select up to 5000 vehicles per day that meet these criteria.

**Comment by Ryanb58** [comment]
Query:
```
select count(1) from vehicles where exterior_colors is NULL or interior_colors is NULL or equipment is NULL;
```

Result:
```
89467
```

**Comment by Ryanb58** [comment]
UVC: 1986040N22
Returns 500 error from BlackBook API.

Ignore these invalid cases?

**Comment by Ryanb58** [comment]
**readVehicleDetails** 

Setup the daily worker schedule. Each lambda has an execution timeout of 15 minutes(max). I was able to successfully process around 30 vehicles each hour before hitting some invalid status codes from BlackBook, so for now, I set the limit to 30 vehicles and am scheduling the worker to run once an hour so we can process around 720 vehicles a day. 

To help mitigate the pain of this slow process... this, I will process the vehicles from newest to oldest...

I will look at BlackBook's API throttling later to see if we can balance this out more so.

**Comment by Ryanb58** [comment]
**readVehicleDetails** 

Setup the daily worker schedule. Each lambda has an execution timeout of 15 minutes(max). I was able to successfully process around 100 vehicles each hour before hitting some invalid status codes from BlackBook, so for now, I set the limit to 100 vehicles and am scheduling the worker to run once an hour so we can process around 2400 vehicles a day. 

To help mitigate the pain of this slow process... this, I will process the vehicles from newest to oldest...

I will look at BlackBook's API throttling later to see if we can balance this out more so.

**Comment by Ryanb58** [comment]
I am running into a response I'm not sure how to handle yet...

```
updateVehicleDetailsFromBlackBook - Response Status Code: 400
updateVehicleDetailsFromBlackBook - Response Json: {'message': 'No colors were found for UVC 2023790927.'}
```

```
updateVehicleDetailsFromBlackBook - FAILURE UVCs: ['2023885020', '2023885014', '2023790941', '2023790933', '2023790932', '2023790931', '2023790930', '2023790929', '2023790928', '2023790927']
```

Which means we are attempting to redo these and they continue to fail again and again.. preventing the worker from moving on. Need to figure out how I should handle these.

**Comment by Ryanb58** [comment]
```

updateVehicleDetailsFromBlackBook - Response Json: {'message': 'No colors were found for UVC 2023540441.'}
updateVehicleDetailsFromBlackBook - Batch completed. Processed 100 vehicles with 100 failures.
updateVehicleDetailsFromBlackBook - FAILURE UVCs: ['2023885020', '2023885014', '2023790941', '2023790933', '2023790932', '2023790931', '2023790930', '2023790929', '2023790928', '2023790927', '2023790926', '2023790925', '2023790924', '2023790919', '2023790725', '2023790721', '2023790225', '2023790224', '2023790217', '2023790215', '2023790189', '2023790188', '2023790187', '2023790186', '2023790179', '2023790178', '2023790177', '2023790176', '2023790173', '2023790172', '2023790167', '2023790166', '2023790165', '2023790164', '2023790162', '2023790158', '2023790157', '2023790156', '2023790155', '2023790154', '2023790153', '2023790139', '2023790135', '2023790134', '2023790129', '2023790128', '2023790127', '2023790098', '2023790095', '2023790089', '2023790088', '2023790084', '2023790083', '2023790080', '2023790079', '2023790076', '2023790075', '2023790059', '2023790052', '2023790039', '2023790038', '2023790037', '2023790036', '2023790033', '2023790032', '2023790031', '2023790030', '2023790022', '2023790021', '2023790020', '2023790019', '2023790018', '2023790017', '2023790016', '2023740P83', '2023730004', '2023730003', '2023640620', '2023640619', '2023640618', '2023640617', '2023640616', '2023640615', '2023640614', '2023640613', '2023640612', '2023640603', '2023640602', '2023640384', '2023640383', '2023640367', '2023640366', '2023640185', '2023640184', '2023560561', '2023560550', '2023560549', '2023540456', '2023540442', '2023540441']


```

**Comment by Ryanb58** [comment]
Upped the limit to 1000.

Last batch results(e263a5df-bcb7-438c-964d-acde48b6266b):
```
updateVehicleDetailsFromBlackBook - Batch completed. Processed 1000 vehicles with 375 failures.

updateVehicleDetailsFromBlackBook - FAILURE UVCs: ['2023885020', '2023885014', '2023790941', '2023790933', '2023790932', '2023790931', '2023790930', '2023790929', '2023790928', '2023790927', '2023790926', '2023790925', '2023790924', '2023790919', '2023790725', '2023790721', '2023790225', '2023790224', '2023790217', '2023790215', '2023790189', '2023790188', '2023790187', '2023790186', '2023790179', '2023790178', '2023790177', '2023790176', '2023790173', '2023790172', '2023790167', '2023790166', '2023790165', '2023790164', '2023790162', '2023790158', '2023790157', '2023790156', '2023790155', '2023790154', '2023790153', '2023790139', '2023790135', '2023790134', '2023790129', '2023790128', '2023790127', '2023790098', '2023790095', '2023790089', '2023790088', '2023790084', '2023790083', '2023790080', '2023790079', '2023790076', '2023790075', '2023790059', '2023790052', '2023790039', '2023790038', '2023790037', '2023790036', '2023790033', '2023790032', '2023790031', '2023790030', '2023790022', '2023790021', '2023790020', '2023790019', '2023790018', '2023790017', '2023790016', '2023740P83', '2023730004', '2023730003', '2023640620', '2023640619', '2023640618', '2023640617', '2023640616', '2023640615', '2023640614', '2023640613', '2023640612', '2023640603', '2023640602', '2023640384', '2023640383', '2023640367', '2023640366', '2023640185', '2023640184', '2023560561', '2023560550', '2023560549', '2023540456', '2023540442', '2023540441', '2023540439', '2023540350', '2023540348', '2023540346', '2023500174', '2023500166', '2023500165', '2023500164', '2023500160', '2023500159', '2023500158', '2023500157', '2023500156', '2023500155', '2023500154', '2023500153', '2023500152', '2023500151', '2023500147', '2023500146', '2023500132', '2023500131', '2023500130', '2023500129', '2023500128', '2023500124', '2023500123', '2023500122', '2023500121', '2023500113', '2023500112', '2023500111', '2023500110', '2023500109', '2023500104', '2023500103', '2023500102', '2023500101', '2023500094', '2023500072', '2023500060', '2023500049', '2023500048', '2023500031', '2023495161', '2023495160', '2023495159', '2023495072', '2023485637', '2023485631', '2023485630', '2023485245', '2023485236', '2023485235', '2023485234', '2023485233', '2023485227', '2023485226', '2023485218', '2023485215', '2023485092', '2023485091', '2023485035', '2023485034', '2023485033', '2023400221', '2023400220', '2023400219', '2023400218', '2023400180', '2023400179', '2023400178', '2023400177', '2023380635', '2023380634', '2023380633', '2023380614', '2023380613', '2023380612', '2023380611', '2023380610', '2023380285', '2023380284', '2023380266', '2023380265', '2023380199', '2023380198', '2023380135', '2023380088', '2023380076', '2023380075', '2023360348', '2023360338', '2023360335', '2023360329', '2023360255', '2023360044', '2023340453', '2023340452', '2023340447', '2023340446', '2023340441', '2023340439', '2023340435', '2023340434', '2023340431', '2023340430', '2023340429', '2023340428', '2023340427', '2023340426', '2023340391', '2023340390', '2023340277', '2023340276', '2023340275', '2023340274', '2023340273', '2023340272', '2023340271', '2023340269', '2023340267', '2023340265', '2023340264', '2023340263', '2023340252', '2023340248', '2023340246', '2023340232', '2023340231', '2023340230', '2023340229', '2023340228', '2023340227', '2023340226', '2023340225', '2023340224', '2023340222', '2023340221', '2023340220', '2023340219', '2023340217', '2023340123', '2023340122', '2023340119', '2023340114', '2023340097', '2023340054', '2023315067', '2023315066', '2023315065', '2023315064', '2023315063', '2023315060', '2023315057', '2023315043', '2023315042', '2023300829', '2023300827', '2023300824', '2023300780', '2023300779', '2023300778', '2023300657', '2023300656', '2023300655', '2023300491', '2023300483', '2023300388', '2023300365', '2023300359', '2023300301', '2023300190', '2023300103', '2023300094', '2023300035', '2023160973', '2023160972', '2023160970', '2023160867', '2023160866', '2023160865', '2023160863', '2023160861', '2023160818', '2023160817', '2023160794', '2023160793', '2023160738', '2023160737', '2023160736', '2023160642', '2023160621', '2023160618', '2023160585', '2023160550', '2023160548', '2023160547', '2023160545', '2023160544', '2023160534', '2023160529', '2023160528', '2023160520', '2023160518', '2023160509', '2023160505', '2023160503', '2023160501', '2023160456', '2023160417', '2023160414', '2023160413', '2023160412', '2023160409', '2023160402', '2023160368', '2023160362', '2023160334', '2023160310', '2023160307', '2023160306', '2023160296', '2023160294', '2023160291', '2023160286', '2023160285', '2023160277', '2023160275', '2023160274', '2023160273', '2023160271', '2023160266', '2023160216', '2023160208', '2023160114', '2023160108', '2023160075', '2023080873', '2023080872', '2023080871', '2023080509', '2023080508', '2023080507', '2023080506', '2023080505', '2023080504', '2023080503', '2023080502', '2023080428', '2023080399', '2023080267', '2023080262', '2023080227', '2023080226', '2023020673', '2023020521', '2023020123', '2023020122', '2023020085', '2023020084', '2023020064', '2023020059', '2022996N09', '2022992N84', '2022992N83', '2022940N41', '2022940N40', '2022940N23', '2022940202', '2022900N50', '2022900N49', '2022900N45', '2022900N44', '2022900N43']
```

**Comment by Ryanb58** [comment]
The worker seems to be getting stuck over time. It retries the failed vehicles with "no colors" and gets stuck when the amount of "no color" uvc's reach the max amount we process each time. Thus the worker never moves on to the rest of the data. 

A solution that I might implement is recording the status returned by BlackBook and skipping any that have already been attempted. That way the worker can move on each run to new "vehicles".

**Comment by Ryanb58** [comment]
Look at the `readVehicleDetails` method in the `3rdPartyHttp` lambda, it looks like we simply return when we do not find any colors for a particular vehicle. This causes no updates and us to retry as exterior_colors, interior_colors, and equipment is set to NULL still.

Previous Code:
```
if len(response['vehicle_colors']['category_list']) == 0:
    return {
        'statusCode': 400,
        'body': {'message': 'No colors were found for UVC ' + data['record']['uvc'] + '.'}
    }
else:
    ...
```

New Code:

```
if len(response['vehicle_colors']['category_list']) == 0:
    print(f"No colors wer efound for UVC: {data['record']['uvc']}")
else:
    ...
```

This will set the values of the `exterior_colors`, `interior_colors`, and `equipment` to empty values that ARE NOT null(like {}, or []). Thus allowing the bulk update script to filter already attempted vehicles.

**Comment by Ryanb58** [comment]
Look at the `readVehicleDetails` method in the `3rdPartyHttp` lambda, it looks like we simply return when we do not find any colors for a particular vehicle. This causes no updates and us to retry as exterior_colors, interior_colors, and equipment is set to NULL still.

Previous Code:
```
if len(response['vehicle_colors']['category_list']) == 0:
    return {
        'statusCode': 400,
        'body': {'message': 'No colors were found for UVC ' + data['record']['uvc'] + '.'}
    }
else:
    ...
```

New Code:

```
if len(response['vehicle_colors']['category_list']) == 0:
    print(f"No colors wer efound for UVC: {data['record']['uvc']}")
else:
    ...
```

This will set the values of the `exterior_color`, `interior_color`, and `equipment` to empty values that ARE NOT null. Thus allowing the bulk update script to filter already attempted vehicles.


#### Query To View Vehicles where we found NO COLORS!
```
select * from vehicles where exterior_colors = '[]' AND interior_colors = '[]' AND equipment = '{}' LIMIT 1000;
```

**Comment by Ryanb58** [comment]
Takes ~13 minutes to run 1000 vehicles. Which is VERY close to the maximum time a lambda can run (15 minutes).

**Comment by Ryanb58** [comment]
Learned something new. 

New vehicles UVCs are alphanumeric.
Used vehicle UVCs are only numeric.

Thus the 500 errors returned by BlackBook are actually meaningful just not explanatory. I'll bypass these 500 errors by ignoring any alpha numeric IDs in the vehicles tables.

**Comment by Ryanb58** [comment]
It takes about 1.09 seconds to complete one vehicle. 
With my constraint of 15 minutes to run. The best amount of vehicles to go through can be calculated using the following formula:

```
1.09 * 800 / 60 = 14.5333333333 minutes.
```

**Comment by billypilgrim88** [comment]
Why not use SQS like Scott is using for the dealerships? That way we don't have any time limits.

**Comment by Ryanb58** [comment]
The time limit ended up not being an issue. The script ran through all the used vehicles already.

I went with this implementation because it was quick to implement. We can refine it w/ SQS later.

**Comment by billypilgrim88** [comment]
Ok, we need to check on the job. I created a view in the database called vehicles_background_job and it looks like we are missing quite a bit of data:

<img width="1482" alt="Screenshot 2023-01-13 at 11 45 29 AM" src="https://user-images.githubusercontent.com/106979142/212373641-d72dd2c7-90f0-446f-831e-b36ccadc307d.png">

**Comment by billypilgrim88** [comment]
I updated the view to break out Null vs. Blank. Null shows that we still haven't processed 21,294 vehicles out of 89,515 total, which means the process should be complete in about a month. My concern are the vehicles with blank values.

**Comment by Ryanb58** [comment]
I was using NULL values to identify vehicles that hadn't been processed yet. 

The vehicles with empty values({}, [], etc..) are vehicles that were "processed" but Blackbook didn't have immediate data for it. We should take a closer look at these vehicles & the blackbook API.

The rest should have data.

**Comment by billypilgrim88** [comment]
Cleaned up the database because there were duplicates based in cpi_uvc.

**Comment by billypilgrim88** [comment]
Things left to do:

1. For years < 1981, split the model and trim into separate columns (12,000) vehicles.
2. Fix the daily job and connect to SQS.
