### ISSUE TITLE
Blocking does not work after resending the code

### ISSUE THREAD

**Issue by TonyaUkrainets** [CarSnoop-Inc/carsnoop-issues#100]
For example: boxaro3937@chnlog.com

User called Resend code 6 times, but still not blocked

![image](https://user-images.githubusercontent.com/112691890/209935481-8e2d0bd6-938e-465e-a6c8-4cd0a3c352df.png)

**Comment by k-tratseuski** [comment]
@TonyaUkrainets done, ready for testing

**Comment by TonyaUkrainets** [comment]
fixed
