### ISSUE TITLE
updateOffer does not change the status of a deleted trade in + does not update vehicle price

### ISSUE THREAD

**Issue by TonyaUkrainets** [CarSnoop-Inc/carsnoop-issues#101]
Case 1
**Steps:**
1. create an offer
2. go to edit mode of the offer
3. delete trade in
4. save changes

**Actual:** the offer has been updated without a trade-in, but the car is in the In Offer status 
**Expected:** the offer has been updated without a trade-in, but the car is in the Available status

Trade in vehicle: 60e5618f-3e9d-423d-9004-5a771d6e1cbf
Transaction: 040d95d4-ce7b-4f62-8ace-065ef231cd1d

**Comment by TonyaUkrainets** [comment]
Case 2
**Steps:**
1. create an offer
2. go to edit mode of the offer
3. edit vehicle price
4. save changes

**Actual:** Vehicle has an old price
**Expected:** According to requirement: update the Retail value of vehicle equal to the Vehicle price from Offer

Vehicle: 176d62f8-d8dc-42a8-aae0-b132af4f01b7
Transaction: 8bb1d3d9-f215-4024-89e3-b357ae7e6a75
![image](https://user-images.githubusercontent.com/112691890/209961064-5f66bc5a-6fa2-4c10-8810-e2085e30fb87.png)

**Comment by k-tratseuski** [comment]
@TonyaUkrainets done, ready for testing

**Comment by TonyaUkrainets** [comment]
fixed
