### ISSUE TITLE
Fix the text in error messages on BE side in accordance with design

### ISSUE THREAD

**Issue by YunchytsK** [CarSnoop-Inc/carsnoop-issues#103]
Need to fix the text in some error messages in order to make it consistent with design.
See content in this file https://docs.google.com/spreadsheets/d/1JFBiDC7aY_pQk0Q0DGItHiSTsi8rLFQOIxUbTzm4cwk/edit?usp=sharing

**Comment by vitalik77795** [comment]
Also to update error message for expired code **verifyEmail** API.
We have : `Verification code has expired.`
Need to be: `The code has expired. Click resend and try again.`

**Comment by k-tratseuski** [comment]
@YunchytsK, @TonyaUkrainets fixed except `validateZipCode`, I can't fix the text for this endpoint since it's a part of 3rd party API

**Comment by TonyaUkrainets** [comment]
fixed
