### ISSUE TITLE
Check transaction status before executing requests

### ISSUE THREAD

**Issue by TonyaUkrainets** [CarSnoop-Inc/carsnoop-issues#106]
1. Execute `cancelOffer` and `declineOffer` requests only for **Offered** status
2. Execute `completeContract` and `terminateContract` request only for **Under Contract** status

**Comment by k-tratseuski** [comment]
@TonyaUkrainets done, ready for testing

**Comment by TonyaUkrainets** [comment]
fixed
cancelOffer 
![image](https://user-images.githubusercontent.com/112691890/210605264-4659ec7b-4858-4fee-b23a-ad2e3c4d02e3.png)

declineOffer 
![image](https://user-images.githubusercontent.com/112691890/210605389-22b28cc3-c166-4950-ae2c-7e356ad784ad.png)

completeContract 
![image](https://user-images.githubusercontent.com/112691890/210605640-c795640b-c577-45b9-ad39-3db533cb8e4b.png)

terminateContract 
![image](https://user-images.githubusercontent.com/112691890/210605762-ba553098-d53c-455d-af87-36d69532edce.png)
