### ISSUE TITLE
"Awaiting payment" -> "Shipping" transition

### ISSUE THREAD

**Issue by reutenkoivan** [CarSnoop-Inc/carsnoop-issues#108]
### Stripe flow
1. The **Buyer** chooses delivery destination addresses.
> It can be local delivery or via using the Runbuggy service

2. The **Buyer** pays for the vehicle and the delivery (if it were chosen).
>After success paying fronted should notify the BE that payment was processed

3. The **Seller** confirms the payment
> * The transaction status is changing to "shipping"
> * if vehicle delivery were chosen, then create a shipment with the `createShipment` API

4. The **Buyer** has the ability to complete the transaction

### Non-Stripe flow
1. The **Seller** confirms the payment
> The transaction status is changing to "shipping"

2. The **Buyer** chooses delivery destination addresses.
> local or via using the Runbuggy service 

3. The **Buyer** pays for the delivery if it wasn't local delivery
> * After success paying fronted should notify the BE that payment was processed
> * FE creates a shipment with the `createShipment` API

4. The **Buyer** has the ability to complete the transaction

**Comment by reutenkoivan** [comment]
# FE-BE interactions proposal
## Stripe flow
1. After the **Buyer** chooses delivery destination addresses:
> FE storage delivery details locally.

2. After the **Buyer** click on the "Check out" button for final payment:
> * FE calls `createPaymentCheckout`.
> * FE navigates to the paying link.
> * After the successful result of paying process:
      * FE calls `some API (1)` for notifying the BE that payment was processed.
      * BE validates payment and if it was ok changes the payment status.
      * FE calls `some API (2)` and **sand the shipping details**.
      * BE saves the shipping details.

3. After the **Seller** clicks on the "Confirm payment" button:
> * FE calls the `confirmPayment` API
> * BE changes transaction/vehicles statuses
> * If were chosen delivery with 3prty service BE updates the transaction and puts into it the `tracking_number`

4. After the **Buyer** clicks on the "Complete the Deal" button:
> * FE calls the `completeShipment` API
> * BE update transaction statuses

---

## Non-Stripe flow
1. After the **Seller** clicks on the **Confirm payment** button:
> * FE calls the `confirmPayment` API
> * BE changes transaction/vehicles statuses

2. After the **Buyer** specifies the delivery details and click on the "Continue" or on the "Pay for shipment" buttons:
> * For the local delivery:
     * FE calls `some API (2)` and **sand the shipping details** (only type).
     * BE saves the shipping details.
> * For the 3pty delivery:
      * FE calls `createPaymentCheckout`.
      * FE navigates to the paying link.
      * After the successful result of paying process:
        * FE calls `some API (1)` for notifying the BE that payment was processed.
        * BE validates payment and if it was ok changes the payment status.
        * FE calls `some API (2)` and **sand the shipping details**.
        * BE saves the shipping details.

3. After the **Buyer** clicks on the "Complete the Deal" button:
> * FE calls the `completeShipment` API
> * BE update transaction statuses

**Comment by reutenkoivan** [comment]
# API contract proposal

### Internal BE scope @k-tratseuski

```typescript
// some API (2)
// Saves the shipments information to the "transaction.shipping"

type LocalShipmentRecord = {
  transaction_id: string
  type: 'local'
}

type RunbuggyShipmentRecord = {
  transaction_id: string
  type: 'runbuggy'
  pickup: {
    street: string
    city: string
    state: string
    zip_code: string
    first_name: string
    last_name: string
    phone: string
    business_name: string
  }
  drop_off: {
    street: string
    city: string
    state: string
    zip_code: string
    first_name: string
    last_name: string
    phone: string
    business_name: string
  }
}

interface ConfirmShipment {
  operation: 'confirmShipment'
  record: LocalShipmentRecord | RunbuggyShipmentRecord
}
```

### 3rd party BE scope @billypilgrim88 

```typescript
/* 
All required data for creating a shipment is available in the transaction object,
that's why we don't need to pass any additional arguments.
*/
interface CreateShipment {
  operation: 'createShipment'
  record: {
    transaction_id: string
  }
}
```

**Comment by reutenkoivan** [comment]
# Open questions:
1. Is it possible to use the `confirmPayment` API for the shipping and vehicle payment validation?

**Comment by billypilgrim88** [comment]
Check the latest Postman for the following:

1. readPayment3rdParty - new API
2. completeShipment - this was not new, has always been there
3. createShipment - updated to only require transaction ID

**Comment by billypilgrim88** [comment]
Done.

**Comment by Skalapendra69** [comment]
# FE-BE interactions proposal
## Stripe flow
1. After the **Buyer** chooses delivery destination addresses:
> FE storage delivery details locally.

2. After the **Buyer** click on the "Check out" button for final payment:
> * FE calls `createPaymentCheckout`.
> * FE navigates to the paying link.
> * After the successful result of paying process:
      * BE Updates the statuses of transaction's payments
      * BE validates paying for the vehicle and the shipping, if it's a success, changes the payment status to something else than "Not Processed".
      * FE calls `addShipmentDetails`.

3. After the **Seller** clicks on the "Confirm payment" button:
> * FE calls the `confirmPayment` API ( BE changes transaction/vehicles statuses)
> * If were chosen delivery with 3prty service:
>   * FE calls the `createShipment` API to create integration with RunBuggy service (BE updates the transaction and puts into it the `tracking_number`)

4. After the **Buyer** clicks on the "Complete the Deal" button:
> * FE calls the `completeShipment` API (BE update transaction statuses)

---

## Non-Stripe flow
1. After the **Seller** clicks on the **Confirm payment** button:
> * FE calls the `confirmPayment` API ( BE changes transaction/vehicles statuses)

2. After the **Buyer** specifies the delivery details and click on the "Continue" or on the "Pay for shipment" buttons:
> * For the local delivery:
     * FE calls `addShipmentDetails` (BE saves the shipping details.).
> * For the 3pty delivery:
>   * FE calls `addShipmentDetails` (BE saves the shipping details.).
>   * FE calls `createPaymentCheckout`.
>   * FE navigates to the paying link.
>   * After the successful result of paying process:
>   * BE validates paying for the shipping, if it's a success, changes the payment status.
>   * FE calls the `createShipment` API to create integration with RunBuggy service (BE updates the transaction and puts into it the `tracking_number`)

3. After the **Buyer** clicks on the "Complete the Deal" button:
> * FE calls the `completeShipment` API (BE update transaction statuses)
