### ISSUE TITLE
Question: How we should use the chat APIs?

### ISSUE THREAD

**Issue by reutenkoivan** [CarSnoop-Inc/carsnoop-issues#109]
Currently, if i call the chat APIs, i get the following error from screenshot. Is it the BE problem, or just misconfiguration from my side?
![image](https://user-images.githubusercontent.com/37533785/210763051-b8077ee0-a750-4386-8894-dde72ce1fdd2.png)

**Comment by k-tratseuski** [comment]
@reutenkoivan I'm not sure, but I think, that you've missed session in headers

**Comment by reutenkoivan** [comment]
yep, in the postman file were incorrect variables in the headers.
