### ISSUE TITLE
updateDealers - new weekly API to check for new and closed dealerships

### ISSUE THREAD

**Issue by billypilgrim88** [CarSnoop-Inc/carsnoop-issues#11]

**Comment by jongilman8** [comment]
readDealerships accepts a zip code, finds all dealerships within 30 miles, and loads them into the DB if they don't exist yet. The background job needs to run for days 1 to 28 of the month. Each day, take the number of zip codes in the DB, divide by 28, and then set the limit to the result of the math, then set the offet to the day of the month. So, for 1,500 zip codes each day, we need to call readDealerships.

**Comment by Ryanb58** [comment]
Hum.. long & lat to zipcode:
https://gis.stackexchange.com/a/353003

**Comment by billypilgrim88** [comment]
I will update readDealerships to accept a zip code since currently it wants latitude and longitude.
