### ISSUE TITLE
add vehicle, Older car flow: 400 error comes due to entering Car condition

### ISSUE THREAD

**Issue by OlgaMalsteva** [CarSnoop-Inc/carsnoop-issues#110]
for this two cars through add vehicle, Older car flow
![image](https://user-images.githubusercontent.com/80024206/210770337-025380b9-0b2b-4f6c-961d-0d18797fa7f7.png)
![image](https://user-images.githubusercontent.com/80024206/210770522-55d57c69-071f-497b-a95b-9b4e8ddafc80.png)
after filling Car condition field:
POST readVehicleValue returns `400 error comes: {"message": "No vehicle was found for VIN ."} `
![image](https://user-images.githubusercontent.com/80024206/210770904-8d852f24-e19b-4dc8-bd6f-f00313273410.png)
so it is not possible to calculate Trade in and Retail value for these vehicles
Could you please check what is wrong with it?

**Comment by TonyaUkrainets** [comment]
Request body:
```
{
    "operation": "readVehicleValue",
    "record": {
        "vin": "",
        "make": "Kia",
        "model": "Forte",
        "year": "2011",
        "trim": "EX 5D Hatchback",
        "mileage": "0",
        "condition": "Extra Clean"
    }
}
```
![image](https://user-images.githubusercontent.com/112691890/210777760-e9c79785-a0af-41d1-8187-e5d809c33c35.png)

**Comment by billypilgrim88** [comment]
Fixed
