### ISSUE TITLE
Create a new table with shipment details

### ISSUE THREAD

**Issue by k-tratseuski** [CarSnoop-Inc/carsnoop-issues#111]
We need to create a new table to store shipment data.
Properties to store:
1) Shipment type (either local delivery or shipment)
2) Pickup and Drop off fields : 

> - street
> - city
> - state
> - zip code
> - contact name
> - contact phone
> - contact email
> - address name
> - notes (not sure that we need to send it to runbuggy, but we have it in [design](https://www.figma.com/file/vrijHvYtoxzczRJk3S7SEa/Deals?node-id=2931%3A126513))

**Comment by reutenkoivan** [comment]
#108

**Comment by billypilgrim88** [comment]
Done:

-- auto-generated definition
create table shipments
(
    id                    uuid not null
        constraint shipments_pk
            primary key,
    created_by            varchar,
    created_on            timestamp(6),
    changed_by            varchar,
    changed_on            timestamp(6),
    notes                 text,
    status                varchar default 'Open',
    transaction_id        uuid
        constraint shipments_transactions_id_fk
            references transactions,
    pickup_street         varchar,
    pickup_city           varchar,
    pickup_state          varchar,
    pickup_zip_code       varchar,
    pickup_first_name     varchar,
    pickup_last_name      varchar,
    pickup_business_name  varchar,
    pickup_phone          varchar,
    dropoff_street        varchar,
    dropoff_city          varchar,
    dropoff_state         varchar,
    dropoff_zip_code      varchar,
    dropoff_first_name    varchar,
    dropoff_last_name     varchar,
    dropoff_business_name varchar,
    dropoff_phone         varchar,
    tracking_number       varchar,
    vehicle               uuid
        constraint shipments_inventory_id_fk
            references inventory,
    trade_in_vehicle      uuid
        constraint shipments_inventory_id_fk_2
            references inventory
);

**Comment by k-tratseuski** [comment]
done, thx
