### ISSUE TITLE
Create a new 3rd party endpoint to check if the payment is paid

### ISSUE THREAD

**Issue by k-tratseuski** [CarSnoop-Inc/carsnoop-issues#112]
We need to have a new endpoint to check if the payment is paid or not.

**Comment by reutenkoivan** [comment]
#108

**Comment by billypilgrim88** [comment]
Done, I will send the latest Postman shortly:

{
    "operation": "readPayment3rdParty",
    "record": {
        "session_id": "cs_test_b1GCkbavksWDJjI5EX44r25oPs06hjUn5oXoUrjdmSobnCe9j2vkX1FjzR"
    }
}
