### ISSUE TITLE
To add dealership name to pickup ad drop_off addresses of contract in readTransaction API

### ISSUE THREAD

**Issue by vitalik77795** [CarSnoop-Inc/carsnoop-issues#116]
Expected result: If seller or buyer is a Dealer → Pickup or Drop-off address should include the name of Dealership. If seller or buyer is a Buyer → Pickup or Drop-off address should not include the name. 

Actual result: Pickup address includes default address name. Drop-off address includes address name.

So, could you please change **address_name** in **pickup** and **drop_off** properties in **readTransaction**:

![image](https://user-images.githubusercontent.com/110094517/211257426-695a2fd7-fa25-4764-96c8-1a1c11515a16.png)

**Comment by k-tratseuski** [comment]
@vitalik77795 done, ready for testing
