### ISSUE TITLE
Subscription BE logic

### ISSUE THREAD

**Issue by TonyaUkrainets** [CarSnoop-Inc/carsnoop-issues#117]
According to the requirements, the following logic must be configured on the BE
![image](https://user-images.githubusercontent.com/112691890/211318529-1de1f4ca-53b9-496f-9e62-483fbd78ce35.png)

Please, could you check if this logic was implemented in BE or is there some improvement needed?

**Comment by billypilgrim88** [comment]
- 1 and 2 are handled by Stripe. 
- 3 is not a valid requirement. 
- 4 is handled by the backend function called checkSubscription.

**Comment by ssysoi** [comment]
https://github.com/CarSnoop-Inc/carsnoop-issues/issues/74 dublicates
