### ISSUE TITLE
"Contact support" API

### ISSUE THREAD

**Issue by Skalapendra69** [CarSnoop-Inc/carsnoop-issues#119]
We need an API for "Contact support" feature.

According the feature description frontend will send two fields:
 - `reason`
 - `message`
so i offer make the api contract this way

## Request
```
{
    "operation": "mailToSupport",
    "record": {
        "reason": "I love CarSnoop",
        "message": "Your developers are the best",
    }
}
```

## Response OK
```
{
    \\ Perhaps here can be nothing. We don't need any info 
}
```

## Response Error
```
{
    "message": "Something went wrong"
}
```

The user email can be extracted from the user session so we don't send it.

**Comment by Skalapendra69** [comment]
UPD. According the feature description a backend should send a confirmation that the user's message is recieved to the user email

**Comment by billypilgrim88** [comment]
Done, use this:

{
    "operation": "contactSupport",
    "record": {
        "reason": "I love CarSnoop",
        "message": "Your developers are the best"
    }
}
