### ISSUE TITLE
Purchase Agreement Template

### ISSUE THREAD

**Issue by billypilgrim88** [CarSnoop-Inc/carsnoop-issues#12]

**Comment by jongilman8** [comment]
A PDF that can pre-fill buyer, seller, and transaction details so that it can simply be signed.

**Comment by ssysoi** [comment]
we can't test the whole Contract creation flow without template

**Comment by billypilgrim88** [comment]
Attached is a draft of the template. Scott was working on some Python code in Lambda to fill this form.

[CarSnoop Purchase Agreement.pdf](https://github.com/CarSnoop-Inc/carsnoop-issues/files/10345285/CarSnoop.Purchase.Agreement.pdf)

**Comment by billypilgrim88** [comment]
I don't agree that you can't test contract creation without this template. Upon creation of a contract, the backend determines which documents are required. This can still take place. We will update the backend to auto-fill this document if the seller does not have their own purchase agreement.

**Comment by ssysoi** [comment]
@TonyaUkrainets

**Comment by billypilgrim88** [comment]
Scott is almost finished with the endpoint.

**Comment by YunchytsK** [comment]
1. once the CarSnoop Purchase Agreement is generated need to update the list of required documents for Seller and Buyer - add Signed CarSnoop Purchase Agreement
2. need endpoint to generate CarSnoop Purchase Agreement

**Comment by k-tratseuski** [comment]
@billypilgrim88 I've rendered html with dummy data. What do you think, is that ok? Should I proceed with real contract data? 
[8e79a2b0-1d27-4d15-9b95-b91a2d01387a.pdf](https://github.com/CarSnoop-Inc/carsnoop-issues/files/10713691/8e79a2b0-1d27-4d15-9b95-b91a2d01387a.pdf)

**Comment by billypilgrim88** [comment]
Yes, please proceed.

**Comment by k-tratseuski** [comment]
The main logic is already in place so you could check it out

**Comment by k-tratseuski** [comment]
@TonyaUkrainets done, ready for testing
