### ISSUE TITLE
Registration and login in LinkedIn without profile picture

### ISSUE THREAD

**Issue by Matroskin94** [CarSnoop-Inc/carsnoop-issues#120]
When we trying to register or login Linkedin user without avatar, back-end returns 502 error, request `readLinkedInProfile`.

**Comment by billypilgrim88** [comment]
Fixed.

**Comment by k-tratseuski** [comment]
@billypilgrim88 your fix is not working

**Comment by billypilgrim88** [comment]
Kostya has fixed this.
