### ISSUE TITLE
Add checkSubscription to createPaymentCheckout

### ISSUE THREAD

**Issue by TonyaUkrainets** [CarSnoop-Inc/carsnoop-issues#122]
According to requirements `For "completed the contract", "make the final payment" and "make the deposit" subscription will be checked on BE side. `

For actions `"make the final payment"` and `"make the deposit"` method `createPaymentCheckout` is called, but it has no `checkSubscription` validation

Could you add the validation?

**Comment by Skalapendra69** [comment]
It should work the same way as `completeContract` works. If internal subscription checking isn't passed `createPaymentCheckout ` should return 400 code so we will be able to understand that the error reason is subscription

**Comment by Skalapendra69** [comment]
Will not do
