### ISSUE TITLE
contactSupport method isn't functioning properly

### ISSUE THREAD

**Issue by AntonZakWork** [CarSnoop-Inc/carsnoop-issues#128]
Requests to `contactSupport` via Postman return internal server error
![Снимок](https://user-images.githubusercontent.com/101989673/212305866-a74bf318-d5a1-4c71-997e-faf11334b976.PNG)
![Снимок123](https://user-images.githubusercontent.com/101989673/212305874-3a5b432d-176e-4bfd-a17e-1dcd723a6598.PNG)

**Comment by billypilgrim88** [comment]
Fixed
