### ISSUE TITLE
Add payment validation to the createPaymentCheckout

### ISSUE THREAD

**Issue by k-tratseuski** [CarSnoop-Inc/carsnoop-issues#131]
We need to add some logic before calling stripe in `createPaymentCheckout` to check:

1. payment exists for this type (e.g Deposit) and transaction id
2. If it exists we need to check was it paid or not (we could use `readPayment3rdParty` for this):
    - if it was paid don't call stripe -> return an error (payment was already paid)
    - if it wasn't paid  -> use remaining `createPaymentCheckout` logic
3. If payment is not exist -> remaining `createPaymentCheckout` logic

**Comment by billypilgrim88** [comment]
Done.
