### ISSUE TITLE
Check the BE logic for counting the deals for subscription

### ISSUE THREAD

**Issue by YunchytsK** [CarSnoop-Inc/carsnoop-issues#132]
**AS-IS:** only deals in status "Delivered" are counted as completed for subscription. So, it could be the case when Buyer has several deals in "Shipping" status and do not move it to "Delivered". Keeping deals in "Shipping" status allows Buyer to make the new deals.

**Possible solution**: to count "Shipping" and "Delivered" deals as completed for subscription. 

Link to objects` statuses flow: https://wiki.andersenlab.com/display/CRSN/Statuses+of+CarSnoop+objects 
![image](https://user-images.githubusercontent.com/117083992/212358165-3a7569e6-1e73-4c12-9607-d03903c51124.png)

**Comment by billypilgrim88** [comment]
@k-tratseuski - if transaction status is in the following, it should count against the subscription:

Offered
Under Contract
Awaiting Payment
Payment Failed
Shipping
Delivered

**Comment by YunchytsK** [comment]
@k-tratseuski 
Under Contract
Awaiting Payment
Shipping
Delivered

**Comment by k-tratseuski** [comment]
@YunchytsK @TonyaUkrainets done, ready for testing

**Comment by TonyaUkrainets** [comment]
fixed
