### ISSUE TITLE
Add permission check for createPaymentCheckout and confirmPayment

### ISSUE THREAD

**Issue by TonyaUkrainets** [CarSnoop-Inc/carsnoop-issues#134]
Add permission check for method `createPaymentCheckout` and `confirmPayment`.
Need check the rights before paying the deposit/car/subscription. To prevent a non-admin from making a payment.

If `user is admin` -> no permission error
If `user is non-admin` -> error `"You have no admin permission"`

**Comment by billypilgrim88** [comment]
Done.
