### ISSUE TITLE
Stripe settings are broken (probably)

### ISSUE THREAD

**Issue by Skalapendra69** [CarSnoop-Inc/carsnoop-issues#135]
When we call `createPaymentCheckout ` method we get Stripe generated error
```
{
  "error": {
    "message": "No valid payment method types for this Checkout Session. Please ensure that you have activated payment methods compatible with your chosen currency in your dashboard (https://dashboard.stripe.com/settings/payment-methods) or specify `payment_method_types`.", 
    "request_log_url": "https://dashboard.stripe.com/test/logs/req_KAfodAFu9KOQL0?t=1673861001", 
    "type": "invalid_request_error"
  }
}
```

Request body

```
{
  "operation":"createPaymentCheckout",
  "record":{
    "transaction_id":"cdf1e73a-66da-4a2c-8ad2-91b445ff0148",
    "success_url":"http://localhost:3000/contracts/cdf1e73a-66da-4a2c-8ad2-91b445ff0148/payment_success?flow=stripe",
    "cancel_url":"http://localhost:3000/contracts/cdf1e73a-66da-4a2c-8ad2-91b445ff0148",
    "items":[
        {
            "amount":3372675,
            "product_name":"Balance",
            "product_description":"Remaining Balance to Seller"
        }
     ]
  }
}
```

**Comment by Skalapendra69** [comment]
Looks like it's working now

**Comment by billypilgrim88** [comment]
The request above is incorrect, you must send decimal points:

{
  "operation":"createPaymentCheckout",
  "record":{
    "transaction_id":"cdf1e73a-66da-4a2c-8ad2-91b445ff0148",
    "success_url":"http://localhost:3000/contracts/cdf1e73a-66da-4a2c-8ad2-91b445ff0148/payment_success?flow=stripe",
    "cancel_url":"http://localhost:3000/contracts/cdf1e73a-66da-4a2c-8ad2-91b445ff0148",
    "items":[
        {
            "amount":33726**.**75,
            "product_name":"Balance",
            "product_description":"Remaining Balance to Seller"
        }
     ]
  }
}

**Comment by Skalapendra69** [comment]
@billypilgrim88 We can't send number like `3372675` with decimal. When i try to send `1234.00` it is converted to `1234` because these numbers are equal. Is it really so required? In that example `3372675` is a integer number

**Comment by k-tratseuski** [comment]
@billypilgrim88, since I was refactoring this endpoint, I've converted prices to the float on our side, so no more reproduced
