### ISSUE TITLE
contactSupport CORS error

### ISSUE THREAD

**Issue by AntonZakWork** [CarSnoop-Inc/carsnoop-issues#136]
Althought it works normally via Postman, there still seems to be a CORS issue with this metod, when it's called through our application

![Снимок](https://user-images.githubusercontent.com/101989673/212666523-379dc57f-1e97-4b26-92b0-78a19a522a59.PNG)
![Снимок12233](https://user-images.githubusercontent.com/101989673/212666813-32874079-7eb2-4ca3-a047-b54099addf35.PNG)

**Comment by billypilgrim88** [comment]
Should be fixed now.
