### ISSUE TITLE
createShipment returns 502 code

### ISSUE THREAD

**Issue by Skalapendra69** [CarSnoop-Inc/carsnoop-issues#137]
Request body
```
{
  "operation":"createShipment",
  "record":{
    "transaction_id":"e3ce853f-d19c-42fc-9285-e4df5306e5c4"
  }
}
```

**Comment by TonyaUkrainets** [comment]
Now createShipment returns 400 code
```
{
    "operation": "createShipment",
    "record": {
        "transaction_id": "65b904fe-f4cb-447f-a777-95166d6256db"
    }
}
```

```
{
    "message": "Shipment creation failed."
}
```

**Comment by billypilgrim88** [comment]
The above transaction does not exist.

**Comment by TonyaUkrainets** [comment]
Transaction exists `af47c261-0b06-4921-a9ff-546d1f59c1f0`
![image](https://user-images.githubusercontent.com/112691890/213401206-f559e9a6-9040-42ef-823a-3e1b81f6a8bf.png)

But the error is reproduced

```
{
    "operation": "createShipment",
    "record": {
        "transaction_id": "af47c261-0b06-4921-a9ff-546d1f59c1f0"
    }
}
```


```
{
    "message": "Shipment creation failed."
}
```

**Comment by Skalapendra69** [comment]
> The above transaction does not exist.

perhaps when you checked it all transactions had been deleted. We cleared DB yesterday

**Comment by TonyaUkrainets** [comment]
But transaction `af47c261-0b06-4921-a9ff-546d1f59c1f0` still exists (it`s a new one) and createShipment doesn`t work

**Comment by k-tratseuski** [comment]
@Skalapendra69 done

**Comment by k-tratseuski** [comment]
working
