### ISSUE TITLE
Subscription info on "Payment method" Stripe page

### ISSUE THREAD

**Issue by Skalapendra69** [CarSnoop-Inc/carsnoop-issues#142]
#### Info for displaying
 - type of selected subscription
 -  amount to pay

![image](https://user-images.githubusercontent.com/50297089/213440169-a281d6c5-a154-43ac-b754-badb8c150e31.png)
![image](https://user-images.githubusercontent.com/50297089/213440499-9264d793-4f51-44f5-874a-e66b78a13908.png)

**Comment by billypilgrim88** [comment]
No, Stripe limits what can appear in the billing portal.
