### ISSUE TITLE
[Support] Fix client email

### ISSUE THREAD

**Issue by TonyaUkrainets** [CarSnoop-Inc/carsnoop-issues#144]
Email should be 
![image](https://user-images.githubusercontent.com/112691890/213501518-69794fbf-a7eb-4308-9821-ab0a8c579ce4.png)

Real example
![image](https://user-images.githubusercontent.com/112691890/213502184-0e154fef-e0b2-433a-bb3b-73424943fea9.png)

**Comment by billypilgrim88** [comment]
We did not agree to this email layout, the layout will stay as it is.
