### ISSUE TITLE
readShipment returns error

### ISSUE THREAD

**Issue by TonyaUkrainets** [CarSnoop-Inc/carsnoop-issues#147]
```
{
    "operation": "readShipment",
    "record": {
        "tracking_number": "033f5e36-1e05-44e9-9d3e-55406562b6fb"
    }
}
```

```
{
    "message": "Shipment does not exist."
}
```

The transaction `f4af6451-f397-49a0-ac84-bb3bd4dfe1f1` has this tracking number
![image](https://user-images.githubusercontent.com/112691890/214031223-15ec822f-8fbe-4d9a-88f8-a18e6a3cacf6.png)

**Comment by k-tratseuski** [comment]
Seems that there is no shipment in runbuggy with such id

**Comment by billypilgrim88** [comment]
The wrong API is being used, readShipment is called by readShipmentDetails. Use readShipmentDetails instead:

{
    "operation": "readShipmentDetails",
    "record": {
        "transaction_id": "f4af6451-f397-49a0-ac84-bb3bd4dfe1f1"
    }
}

**Comment by TonyaUkrainets** [comment]
The problem is that `readShipmentDetails` does not return a `iframe` parameter.
We need it to display a map for the user with the delivery of the car

**Comment by k-tratseuski** [comment]
@billypilgrim88. `readShipmentDetails` is responsible only for showing "shipment details" (the data that buyer could modify for the real shipment). That details where added by `addShipmentDetails`. And `readShipmentDetails` is only used in `createShipment` to get all necessary data for **RunBuggy** directly from DB, but not from request.

So the problem seems in our flow. We create an order in **RunBuggy** through `createShipment` and then we update our `shipment` table in db and setting `tracking_number`. In the end of the day we want to track our shipment and for this we call `readShipment`, that is responsible for calling `RunBuggy` [endpoint](https://docs.runbuggy.com/docs/shipping-api/ff52f90460b19-retrieve-a-vehicle-transfer-order) and it returns us 404. But I tried to call [this](https://docs.runbuggy.com/docs/shipping-api/43f111399e7fa-retrieve-an-order) with the same tracking_number and it worked. I'm not too familiar with RunBuggy API, but we need to understand what we are doing wrong

**Comment by billypilgrim88** [comment]
The issue occurs when there is more than one vehicle in the order, i.e. a trade-in. Working on a fix.

**Comment by billypilgrim88** [comment]
Fixed, there is a new key in the response called transfers:

{
    "orderId": "033f5e36-1e05-44e9-9d3e-55406562b6fb",
    "iframe": "https://ng-staging.runbuggy.com/staging-green/spa-v2/#/external/order-status?orderId=033f5e36-1e05-44e9-9d3e-55406562b6fb&token=eyJhbGciOiJSUzI1NiIsInR5cCI6IkpXVCJ9.eyJqdGkiOiJmNjE2MjhkNC00NGE1LTQ3NTAtYWQ2MS05MzI0Y2E4NDFmOWIiLCJpc3MiOiJodHRwczovL2FwcHMucnVuYnVnZ3kuY29tIiwiaWF0IjoxNjU4ODQ4MTExfQ.Nt0yIs7icOpU1HXxHSWEG75GNK90iKEIL_NjNpB0NcpgZ6Je04zXe36e5FqU5-GRkVSyvBZBcDV_al9lxiQNfTTlGb4VK6rkDIvK0g9yx_bbhXtmCzZ8yULwggnjJoqG1ho8yCGZ7GzAp6wPgQrC0c3HskSe8s7Ij8l5iViVWJmBugrWDwLQrsIfXLyKbN6dvBQ5A8al_0kejSFhGAI2xv7wc0-8n4cz2Oh35U9FGgL0UpxVu-H0R1HB2EEtHxklK3xHIkn_KcTJV_tMthd8mJeov3_RnoFlVoSu7DS7y3HaEVpAGnNd1Fn2QsPV5FIYayju7yRkbtEmcbke4LTfNQ&sections=MAP,STATUS_BAR,TIMELINE",
    "transfers": [
        {
            "pickup": {
                "name": "",
                "address": "480 W Poplar St #123, Zionsville, IN 46077, USA",
                "contact": "Mary Rosen",
                "phone": "1119998880"
            },
            "dropoff": {
                "name": "Fishers Imports Luxury Used Cars",
                "address": "4529 W 96th St, Indianapolis, IN 46268, USA",
                "contact": "Cool Dealer",
                "phone": "1119998880"
            },
            "vehicle": {
                "year": 2022,
                "make": "Acura",
                "model": "ILX",
                "stockNumber": "",
                "isOverSized": false,
                "isOperational": true,
                "notes": "Have a good day! Have a good day!Have a good day!Have a good day!Have a good day!Have a good day!Have a good day!Have a good day!Have a good day!Have a good day!Have a good day!Have a good day!Have a good day!Have a good day!Have a good day!Have a good day!Have a good day!Have a good day!Have a good day!Have a good day!Have a good day!Have a good day!Have a good day!Have a good day!Have a good day!Have a good day!Have a good day!Have a good day!Have a good day!Have a good day!Have a good day!Have a good day!Have a good day!Have a good day!Have a good day!Have a good day!Have a good day!Have a good day!Have a good day!Have a good day!Have a good day!Have a good day!Have a good day!Have a good day!Have a good day!Have a good day!Have a good day!Have a good day!Have a good day!Have a good day!Have a good day!Have a good day!Have a good day!Have a good day!Have a good day!Have a good day!Have a good day!Have a good day!Have a good day!Have a good day!Have a good day!Have a good day!Have a good day!Have a good day!Have a good day!Have a good day!Have a good day!Have a good day!Have a good day!Have a good day!Have a good day!Have a good day!Have a good day!Have a good day!Have a good day!Have a good day!Have a good day!Have a good day!Have a good day!Have a good day!Have a good day!Have a good day!Have a good day!Have a good day!Have a good day!Have a good day!",
                "odometer": 12345678,
                "vin": "19UDE2F81NA006717"
            }
        },
        {
            "pickup": {
                "name": "Fishers Imports Luxury Used Cars",
                "address": "4529 W 96th St, Indianapolis, IN 46268, USA",
                "contact": "Cool Dealer",
                "phone": "1119998880"
            },
            "dropoff": {
                "name": "",
                "address": "480 W Poplar St #123, Zionsville, IN 46077, USA",
                "contact": "Mary Rosen",
                "phone": "1119998880"
            },
            "vehicle": {
                "year": 2022,
                "make": "Acura",
                "model": "ILX",
                "stockNumber": "123",
                "isOverSized": false,
                "isOperational": true,
                "notes": "",
                "odometer": 0,
                "vin": ""
            }
        }
    ]
}

**Comment by k-tratseuski** [comment]
@billypilgrim88 It's not working again. Now the problem is that if we don't have trade-in it returns 404 from RunBuggy. But I tried [endpoint](https://docs.runbuggy.com/docs/shipping-api/ff52f90460b19-retrieve-a-vehicle-transfer-order) (1) and it worked. It seems that we need to call different endpoints for deal with (endpoint 2) and without trade-in (endpoint 1).

**Comment by k-tratseuski** [comment]
@billypilgrim88 tracking number without trade-in `bbc352e4-866f-4841-9c7c-925f8ab06934`

**Comment by k-tratseuski** [comment]
@billypilgrim88 
![image](https://user-images.githubusercontent.com/117080223/214562625-9cab9526-5cf9-43ea-ad05-33806357c214.png)

**Comment by billypilgrim88** [comment]
Looks like it's working now.
