### ISSUE TITLE
Add the vehicle photo to the readChats API response

### ISSUE THREAD

**Issue by reutenkoivan** [CarSnoop-Inc/carsnoop-issues#150]
From the design perspective, we need to display the vehicle image if it exists, otherwise, we need to display the default image which is stored in our app.

![image](https://user-images.githubusercontent.com/37533785/214254474-f43b6624-e150-4113-88c1-c15193939254.png)

https://user-images.githubusercontent.com/37533785/214265449-f6306010-a139-4aeb-98e2-4c0ead36a2be.mov

**Comment by reutenkoivan** [comment]
As I correctly understood the vehicle photo processing, you need to find the image with truly `thumbnail` property and send it, if this photo exists, of course.

**Comment by reutenkoivan** [comment]
> Should the thumbnail come back in the readChats api response under the inventory key?

Yes

> What should the value be? A URL? Base64 encoded? UUID?

It should be a URL.

You can see an example in response from the `readTransaction` API by the 'vehicle.document_content' path.

```json
{
    "operation": "readTransaction",
    "record": {
        "id": "c9a2ff67-bd54-4309-936a-3f285b315164"
    }
}
```

![image](https://user-images.githubusercontent.com/37533785/214891636-899e78da-acb1-4e90-90c9-c8902f24652e.png)

**Comment by k-tratseuski** [comment]
@scottwoodall The idea is the same as [here](https://github.com/CarSnoop-Inc/carsnoop-issues/issues/172#issuecomment-1420373599)

All you need is to filter documents table properly with help of vehicle's id

```python
vehicle_id = "some vehicle's id here"
cursor.execute(
    """
        SELECT id, type 
        FROM documents 
        WHERE thumbnail = TRUE AND object_type = 'vehicle' AND object_id = %s
    """,
    (vehicle_id, )
)
thumbnail = cursor.fetchone()
thumbnail_link = f"{os.environ['ImageUrl']}{thumbnail['id']}.{thumbnail['type']}" if thumbnail else ""
```

**Comment by Skalapendra69** [comment]
Thanks, it works

**Comment by Ryanb58** [comment]
Don't forget to use presigned URLs when available as the direct s3 URLs defined in this tread won't work when/if we take the bucket private so other people can't easily scrape our data.

@scottwoodall  you can find an example of how to generate pre-signed urls in the `[fileFunctions](https://us-east-2.console.aws.amazon.com/lambda/home?region=us-east-2#/functions/fileFunctions)` lambda.

**Comment by k-tratseuski** [comment]
@Ryanb58 we don't use presigned url for vehicle's photos. We use that new logic only for contract docs and chat docs
