### ISSUE TITLE
To add notes to pickup and drop-off objects in readTransaction

### ISSUE THREAD

**Issue by vitalik77795** [CarSnoop-Inc/carsnoop-issues#151]
Need to add notes fields to drop_off and pickup objects of readTransacrion. We use this information on UI in our forms.
![image](https://user-images.githubusercontent.com/110094517/214283926-0301a38d-be6f-4f1d-8522-b11dbe9badcd.png)

**Comment by k-tratseuski** [comment]
@vitalik77795 done, ready for testing
