### ISSUE TITLE
Wrong verification code assigned to the user - user can't register via invitation link

### ISSUE THREAD

**Issue by OlgaMalsteva** [CarSnoop-Inc/carsnoop-issues#152]
When user iamolgamaltseva@gmail.com registering through an invitation link on the login button, a 400 code is received due to wrong verification_code value
Request URL: https://fhvh05dgg0.execute-api.us-east-2.amazonaws.com/dev/data
Request Method: POST
Status Code: 400 
![image](https://user-images.githubusercontent.com/80024206/214521561-3b6eef0a-bee2-4269-b273-9cbbab274f55.png)
![image](https://user-images.githubusercontent.com/80024206/214521388-aa20da6d-243b-4602-b6e0-394963cca2fe.png)

**Comment by k-tratseuski** [comment]
Not reproduced
