### ISSUE TITLE
Show transactions instead of vehicles on home page. 

### ISSUE THREAD

**Issue by Matroskin94** [CarSnoop-Inc/carsnoop-issues#153]
Create new type for readTransaction, that will output transactions with such statuses: REQUESTED, OFFERED, UNDER CONTRACT. 

Within each group vehicles should be ordered based on time period how long the status was changed → the newest should be displayed at the top, the oldest are at the bottom.

**Comment by k-tratseuski** [comment]
Decided to add `transaction_id` for vehicles in status 'Offered' and 'Under Contract'
