### ISSUE TITLE
Add the ability to send media messages. 

### ISSUE THREAD

**Issue by reutenkoivan** [CarSnoop-Inc/carsnoop-issues#154]
From the design perspective user, in chat, should have the ability to send different files: audio, video, documents and etc.

### [Link to design](https://www.figma.com/file/vrijHvYtoxzczRJk3S7SEa/Deals?node-id=3567%3A110073&t=RsategXU4aIUALE9-4)

Could you please implement that, and/or give an example of usage?

**Comment by reutenkoivan** [comment]
I've tried to send a media message and got an error. Am I doing something wrong?

![image](https://user-images.githubusercontent.com/37533785/215114113-652a61d6-9639-4e68-a45c-0268cf27f921.png)

![image](https://user-images.githubusercontent.com/37533785/215114312-4fc64d31-f570-44d0-be33-be3f5facfe77.png)

**Comment by reutenkoivan** [comment]
In design we can see that the user has the ability to send a file without a message, could you make the message property optional?

![image](https://user-images.githubusercontent.com/37533785/215416663-6446f48e-caa6-4dbb-9105-ea89ec4bae67.png)

![image](https://user-images.githubusercontent.com/37533785/215417482-92dd4caa-a656-4a46-ba68-8dddd8b2a2bc.png)

**Comment by reutenkoivan** [comment]
And one more question, do we really need the `to_user` property? From the business 
perspective, we have some cases when there can be several buyers or dealers in the chat, and it looks like we send a message to all of them.

**Comment by k-tratseuski** [comment]
done
