### ISSUE TITLE
Need to add new field to APIs when subscription error appears

### ISSUE THREAD

**Issue by vitalik77795** [CarSnoop-Inc/carsnoop-issues#156]
Now a few API can return 400 code it two cases:
 - A subscription is expired
 - Another error

To get a real reason of the error lets add an additional field `reason` to error response of the following API's 
- completeContract
- createOffer

An idea is - if the reason of error is expired subscription these API's returns error as
```
code 400
{
  "message": "any message",
  "reason": "invalidSubscription"
}
```
so we will be able to determine that the error cause is subscription

**Comment by k-tratseuski** [comment]
@vitalik77795 @Skalapendra69 done, ready for testing
