### ISSUE TITLE
amount_owed parameter is not saved on BE

### ISSUE THREAD

**Issue by TonyaUkrainets** [CarSnoop-Inc/carsnoop-issues#157]
Vehicle `40af0280-ad4a-4d0e-98c4-61472db3d22f`

createVehicle has `amount_owed` parameter 
![image](https://user-images.githubusercontent.com/112691890/215134108-c900c5ac-0905-4e18-aadc-c6c327a92ac5.png)

readVehicle returnes ``amount_owed:null``
![image](https://user-images.githubusercontent.com/112691890/215134464-ce95a23b-cc19-4db9-955d-faacdcce8033.png)

**Comment by k-tratseuski** [comment]
@TonyaUkrainets done, ready for testing

**Comment by TonyaUkrainets** [comment]
fixed
![image](https://user-images.githubusercontent.com/112691890/215724191-c9371a79-3a77-48a4-9e53-5444b3899d92.png)

**Comment by TonyaUkrainets** [comment]
fixed
![image](https://user-images.githubusercontent.com/112691890/215726036-916d40d4-9e30-486e-a3fb-ab403b612963.png)
