### ISSUE TITLE
updateSubscription returns "No such subscription" error

### ISSUE THREAD

**Issue by TonyaUkrainets** [CarSnoop-Inc/carsnoop-issues#159]
When updating a subscription on one of the accounts, such an error is returned.
We suspect that this is a problem on Stripe's side.
Is it possible to check if everything is OK with the account in the stripe?
```
{
    "operation": "updateSubscription",
    "record": {
        "account_id": "302ae99a-d895-47e7-98d3-117d0378d1cf",
        "type": "Large",
        "return_url": "https://portal-dev.carsnoop.com/subscription?autoupdate&subtype=Large"
    }
}
```

```
{
    "error": {
        "code": "resource_missing",
        "doc_url": "https://stripe.com/docs/error-codes/resource-missing",
        "message": "No such subscription: 'sub_1MUX9ZEZ3w8tMtYcASdxoROW'",
        "param": "id",
        "request_log_url": "https://dashboard.stripe.com/test/logs/req_eTInMixDiWGUT4?t=1675083286",
        "type": "invalid_request_error"
    }
}
```

**Comment by k-tratseuski** [comment]
@billypilgrim88 This message we receive from some Stripe endpoint, seems that something is missing

**Comment by billypilgrim88** [comment]
This subscription was deleted already on January 26th, but it still appears in the database. Lines 2185 - 2190 in updateSubscription have be commented out to avoid this in the future.
