### ISSUE TITLE
Add environment variables to github

### ISSUE THREAD

**Issue by Matroskin94** [CarSnoop-Inc/carsnoop-issues#163]
On web-application we moved configuration data to environment variables, so we need to add this variables in github actions on projects. Need new secret variables.

For dev environment
```
secrets.DEV_AWS_API_KEY - AWS api key
secrets.DEV_LINKEDIN_CLIENT_ID - linkedin key
secrets.DEV_GOOGLE_CLIENT_ID - google key

secrets.DEV_INTERNAL_API_ENDPOINT - internal API endpoint
secrets.DEV_NOTIFICATIONS_API_ENDPOINT - notification APU endpoint
secrets.DEV_CHATS_API_ENDPOINT - chats API endpoint
secrets.DEV_EXTERNAL_API_ENDPOINT - external API endpoint`
```

For production environment
```
secrets.PROD_AWS_API_KEY - AWS api key
secrets.PROD_LINKEDIN_CLIENT_ID - linkedin key
secrets.PROD_GOOGLE_CLIENT_ID - google key

secrets.PROD_INTERNAL_API_ENDPOINT - internal API endpoint
secrets.PROD_NOTIFICATIONS_API_ENDPOINT - notification APU endpoint
secrets.PROD_CHATS_API_ENDPOINT - chats API endpoint
secrets.PROD_EXTERNAL_API_ENDPOINT - external API endpoint
```
  
  Adding this variables should be synchronized with mergin of this [PR](https://github.com/CarSnoop-Inc/carsnoop-web/pull/894)
  
  First need to add variables to github, and next build should be this PR.

**Comment by AntonZakWork** [comment]
You also should add links to mobile applications, we put them into .env variables too
For dev environment: 
`secrets.DEV_APPSTORE_LINK - link to appstore
secrets.DEV_GOOGLE_PLAY_LINK - link to google play`

For production environment: 
`secrets.PROD_APPSTORE_LINK - link to appstore
secrets.PROD_GOOGLE_PLAY_LINK - link to google play`

Please, initialize this values with current mock link (https://carsnoop.com/coming-soon)

**Comment by Skalapendra69** [comment]
### Another one update:
#### For a chat there can be:
 - For dev environment:
```
secrets.DEV_UPDATE_CHAT_PERIOD - how often to get new messages (in milliseconds)
secrets.DEV_UPDATE_CHATS_PERIOD - how often to update all chats info (in milliseconds)
```

 - For production environment:
```
secrets.PROD_UPDATE_CHAT_PERIOD - how often to get new messages (in milliseconds)
secrets.PROD_UPDATE_CHATS_PERIOD - how often to update all chats info (in milliseconds)
```

if these values are not presented default values are:
 - DEV_UPDATE_CHAT_PERIOD - 1000
 - DEV_UPDATE_CHATS_PERIOD - 3000

**Comment by Skalapendra69** [comment]
Two difference environments were created:
 - development
 - production
 
Every of them contains secrets and variables  that are required for the APP building.
For now they are the same and can be changed independently in the future for different builds for dev/prod purposes
