### ISSUE TITLE
Letters to support

### ISSUE THREAD

**Issue by TonyaUkrainets** [CarSnoop-Inc/carsnoop-issues#165]
We want to make sure that support receives letters sent by the user
Could you check and let us know if emails are coming to support@carsnoop.com?

For example, did a letter with such text reach you?
![image](https://user-images.githubusercontent.com/112691890/215779503-8733b2ff-43f9-4097-bf98-897c1288d4b2.png)

**Comment by billypilgrim88** [comment]
Yes.
