### ISSUE TITLE
Add check for updateOffer

### ISSUE THREAD

**Issue by TonyaUkrainets** [CarSnoop-Inc/carsnoop-issues#167]
The method must be triggered for an offer in the `Open` status.
+the Buyer should not be able to update the offer.

**Comment by k-tratseuski** [comment]
@TonyaUkrainets done, ready for testing

**Comment by TonyaUkrainets** [comment]
fixed
![image](https://user-images.githubusercontent.com/112691890/216330689-0e68493a-e9f5-41d2-a66c-edc41bef4ee6.png)


![image](https://user-images.githubusercontent.com/112691890/216331229-3b9f67aa-0abf-47a1-992b-3ba84564b18b.png)
