### ISSUE TITLE
Add check for declinePayment

### ISSUE THREAD

**Issue by TonyaUkrainets** [CarSnoop-Inc/carsnoop-issues#168]
The method should work for transactions in the status "Awaiting Payment"

**Comment by k-tratseuski** [comment]
@TonyaUkrainets it's already implemented

**Comment by TonyaUkrainets** [comment]
works
![image](https://user-images.githubusercontent.com/112691890/216332952-e8f24a57-021c-4a8d-b82d-5d9abea40049.png)
