### ISSUE TITLE
Inventory Functions

### ISSUE THREAD

**Issue by billypilgrim88** [CarSnoop-Inc/carsnoop-issues#17]
Daily functions to scrape the car websites and update our inventory in the database and save car pictures in S3.

**Comment by jongilman8** [comment]
Example: https://www.edmartinbuickgmc.com/searchused.aspx

1. Loop through accounts table where is_dealer = True, use website field to scrape their site (~18,000 dealerships)
2. For listings not in the inventory table, add them. Add images to documents table and load images into S3. The documents table has a thumbnail flag that is used for the primary image.
3. For inventory rows no longer on the site, flag for deletion

**Comment by billypilgrim88** [comment]
Here is the initial code: https://us-east-2.console.aws.amazon.com/lambda/home?region=us-east-2#/functions/inventory?fullscreen=true&tab=code

**Comment by ssysoi** [comment]
redblacktree - Dustin?

**Comment by billypilgrim88** [comment]
Yes, Dustin is redblacktree

**Comment by ssysoi** [comment]
![image](https://user-images.githubusercontent.com/56298532/224088127-128fcff0-6e64-4768-b923-e2ac06f65aa5.png)
https://smartproxy.com/proxies/datacenter-proxies/pricing

**Comment by ssysoi** [comment]
for AWS we will use Kostya's credentials

**Comment by pozernishku** [comment]
@billypilgrim88 would it be good to create a separate table for scraped data for now?

**Comment by billypilgrim88** [comment]
It's a dev environment, it's OK to have bad data.

**Comment by Ryanb58** [comment]
I was able to add the cloudscraper and bs4 dependencies to the `inventory` function. Please review the PR and its description here:

https://github.com/CarSnoop-Inc/carsnoop-backend/pull/20

TODO:
 - Update the current truckpaper scraper to put it's data into the database (or hit an existing API?).
 - Call the lambda function using Cloudwatch Events at night for EACH site.
 - Add more scrapers to the lambda.

**Comment by pozernishku** [comment]
I don't have access to this repository

**Comment by pozernishku** [comment]
In this [PR](https://github.com/CarSnoop-Inc/carsnoop-backend/pull/21) I've prepared a basic scraper for 18 Dealeron sites. There are two requests (new and used inventory) per dealer. This API returns the inventory for all pages at once. The API looks straightforward, but some fields (needed in our createVehicle) are absent in JSON and can be scraped from the HTML page:
- mileage
- retail_price exists in JSON, but there is no f.e. Andy's price (do we need it as well?, it is in HTML)
- exterior_color
- interior_color

To scrape these fields additional scraper development would be needed (including pagination). Should I proceed with this development or it would be ok to set nulls for now?

**Comment by pozernishku** [comment]
@redblacktree @Ryanb58

**Comment by billypilgrim88** [comment]
Add website platform to inventory table.

**Comment by pozernishku** [comment]
I've finished with the first working version (insert to DB only) [here](https://github.com/CarSnoop-Inc/carsnoop-backend/pull/24). Please review @redblacktree @Ryanb58 @k-tratseuski

**Comment by pozernishku** [comment]
The scraped inventory for the `dealeron.com` websites has been imported. Also, the `website_platform` field added.
Update mechanism is the next thing to do (see, some details [here](https://github.com/CarSnoop-Inc/carsnoop-backend/pull/24#pullrequestreview-1356244610)).

**Comment by pozernishku** [comment]
Implemented inventory sync function instead of inventory inserting (see [here](https://github.com/CarSnoop-Inc/carsnoop-backend/pull/26)). Please review @k-tratseuski

**Comment by pozernishku** [comment]
@billypilgrim88 

Some fields coming from dealers require to be mapped properly with Carsnoop (I guess we need to determine the accepted values for these fields in order to be able to create various filters in the future).
- **fuel_type**
- condition
- engine_description
- maybe some others

Also, I've finished with [scrapers for dealerinspire](https://github.com/CarSnoop-Inc/carsnoop-backend/pull/27). I deployed the [inventory lambda](https://us-east-2.console.aws.amazon.com/lambda/home?region=us-east-2#/functions/inventory?tab=code) and scraped the dealerinspire sites from the list (data is already in DB to test). See [indy-dealers](https://docs.google.com/spreadsheets/d/1w7r3NkZNKea1HU4g3yOzFrlttS0s_cQb4CcUX8NIXKU/edit?usp=sharing) sheet for more info. There is one column '**Done dealerinspire**' for finished scrapers. See also comments on some of them.

**Comment by billypilgrim88** [comment]
> @billypilgrim88
> 
> Some fields coming from dealers require to be mapped properly with Carsnoop (I guess we need to determine the accepted values for these fields in order to be able to create various filters in the future).
> 
> * **fuel_type**
> * condition
> * engine_description
> * maybe some others
> 
> Also, I've finished with [scrapers for dealerinspire](https://github.com/CarSnoop-Inc/carsnoop-backend/pull/27). I deployed the [inventory lambda](https://us-east-2.console.aws.amazon.com/lambda/home?region=us-east-2#/functions/inventory?tab=code) and scraped the dealerinspire sites from the list (data is already in DB to test). See [indy-dealers](https://docs.google.com/spreadsheets/d/1w7r3NkZNKea1HU4g3yOzFrlttS0s_cQb4CcUX8NIXKU/edit?usp=sharing) sheet for more info. There is one column '**Done dealerinspire**' for finished scrapers. See also comments on some of them.

I would not worry too much about the field mapping, they can be blank in a lot of cases. At a minimum we need make, model, year, VIN and images. That will allow us to process deals. We can make the data mapping better over time.

**Comment by pozernishku** [comment]
> Do we have a dealerinspire example with pictures in S3?

No. For now, only [dealer.com scraper](https://github.com/CarSnoop-Inc/carsnoop-backend/pull/32) can scrape all pictures. But only scrape. There is still no function to save these pictures to the database.

**Comment by pozernishku** [comment]
See [details](https://github.com/CarSnoop-Inc/carsnoop-backend/pull/35) about dealeron.com photos. I'll add all Indiana dealeron (with photos) to the [daily autostart](https://us-east-2.console.aws.amazon.com/lambda/home?region=us-east-2#/functions/inventoryRunner?tab=code) today.
