### ISSUE TITLE
The chat incognito mode and user avatar

### ISSUE THREAD

**Issue by Skalapendra69** [CarSnoop-Inc/carsnoop-issues#172]
According a [design](https://www.figma.com/file/vrijHvYtoxzczRJk3S7SEa/Deals?node-id=3298%3A105118&t=xcwJgY3MBLAe4XGS-0) and business requirements we have to display user names and avatars if a transaction is in a one of the following statuses:

1.    "Under contract";
2.    "Awaiting payment";
4.    "Shipping";
5.    "Contract Terminated";
6.    "Payment Failed";
7.    "Delivered".

So, my idea is if the transaction isn't in of these statuses `readChatMessages` returns 
```
{
  ...,
  "from_user": "Buyer" | "Seller" // <--- depends on the user role in the deal,
  "avatar": "" // empty string or null, doesn't matter
}
``` 

If the transaction is in one of the statuses `readChatMessages` returns 
```
{
  ...,
  "from_user": "Name Surname"
  "avatar": "src_to_avatar"
``` 

We can't check the transaction on our side and hide users data because of it isn't secure, the data is presented in a response.
So it must be handled on BE side

**Comment by Skalapendra69** [comment]
The same data and logic should be applied to `readChats` API.

**Comment by Skalapendra69** [comment]
> > The same data and logic should be applied to `readChats` API.
> 
> I don't think any user data is exposed in `readChats`.

Yes, it's true, my mistake. 
We are waiting for [this](https://github.com/CarSnoop-Inc/carsnoop-issues/issues/150) issue regarding `readChats`

**Comment by Skalapendra69** [comment]
![image](https://user-images.githubusercontent.com/50297089/216908376-43e12bbc-fdda-4d3c-bd7d-2f269eda86ee.png)
The incognito data is got for a `awaiting payment` transaction

**Comment by Skalapendra69** [comment]
@scottwoodall Did you delete `has_read` field?

**Comment by Skalapendra69** [comment]
@scottwoodall Also we need 'avatar' field in a message

**Comment by Skalapendra69** [comment]
We need both types of avatar. For messages it should be a user avatar. 
If it is incognito it can be empty. If it isn't there should be url 
![image](https://user-images.githubusercontent.com/50297089/217166968-67c54c31-9144-454c-b54c-a6e23b59fcf1.png)

it can be a field of `readChatMessages` response
```
{
  "data": {
      "chats": [
        {
            ...
            "user_avatar" : "url_of_the_user_avatar"
        }
       ]
   }
}
```
---
Regarding vehicle avatar.
It is a photo of transaction vehicle. We need it for chats list
![image](https://user-images.githubusercontent.com/50297089/217168153-d5cbce05-c963-4e8f-a0a8-38387d97f713.png)
 
it can be a field of `readChats` response
```
{
  "data": {
      "chats": [
        {
            ...
            "chat_avatar" : "url_of_the_transaction_vahicle_image",
            "unread" : 1,
            "inventory" : {...},
            "last_message" : {...},
        }
       ]
   }
}
```

**Comment by k-tratseuski** [comment]
@scottwoodall. Currently we have 2 buckets:
1) For vehicle photos, avatars - public bucket
2) For contract documents, etc - private bucket

So if you want to get avatar link you need to something like this:
```python
cursor.execute(
    """
        SELECT id, type 
        FROM documents 
        WHERE name = 'Avatar' AND object_type = 'user' AND object_id = %s
    """,
    (user_id, )
)
avatar = cursor.fetchone()
avatar_link = f"{os.environ['ImageUrl']}{avatar['id']}.{avatar['type']}" if avatar else ""
```

**Comment by Skalapendra69** [comment]
Thanks, it works
