### ISSUE TITLE
[readChats] Chat ordering

### ISSUE THREAD

**Issue by TonyaUkrainets** [CarSnoop-Inc/carsnoop-issues#180]
According to requirements: `The chats should be displayed from newest to oldest based on the date and time of last message.`

**Comment by TonyaUkrainets** [comment]
Messages should be sorted in reverse order, in descending order

**Comment by k-tratseuski** [comment]
@scottwoodall Still can be reproduced (check the screenshot). I'm not sure but maybe we need to add ordering by `sent_on` where we are selecting from named query `user_chats` and remove ordering from that named query. And also I didn't get why should we order by transaction id on the named query, seems that combined ordering leads to this behaviour. What do u think?
![image](https://user-images.githubusercontent.com/117080223/217546114-b3d9d783-0339-4d74-a4d7-b7644a0a7b27.png)

**Comment by TonyaUkrainets** [comment]
fixed
