### ISSUE TITLE
Add new image formats

### ISSUE THREAD

**Issue by k-tratseuski** [CarSnoop-Inc/carsnoop-issues#182]
It's needed to support uploading of heic/heif formats. Currently it's not working.

**Expected result:** File is sent. There is no preview, file can be downloaded.
**Actual result:** File is not sent, `createChatMessage` returns 400, content_type is empty
![image](https://user-images.githubusercontent.com/117080223/217853628-867a5bf2-8263-4e94-aecb-2186b5bb9362.png)

Not sure where is the problem: on the chat side (@scottwoodall ) or on the media side (@Ryanb58 )

**Comment by k-tratseuski** [comment]
@scottwoodall hm, we will check

**Comment by TonyaUkrainets** [comment]
Found out that the problem is reproduced only on Windows.
Since the formats are specific to iOS, they do not interact with Windows in any way. MacOS knows how to work with them. We leave it as is.
