### ISSUE TITLE
Old photo of driver's license is not deleted

### ISSUE THREAD

**Issue by TonyaUkrainets** [CarSnoop-Inc/carsnoop-issues#187]
User kimik77155@laserlip.com / 12345678

The user registered, added a driver's license, then the user was deleted.
Then the user logged in again.
We see that the driver's license photo has been saved.
It would be correct to delete photos after deleting a user.

**Comment by k-tratseuski** [comment]
@TonyaUkrainets done, ready for testing

**Comment by TonyaUkrainets** [comment]
fixed
