### ISSUE TITLE
deleteUser 502 error

### ISSUE THREAD

**Issue by TonyaUkrainets** [CarSnoop-Inc/carsnoop-issues#188]
x-session-id:9e34f47f-c7f0-41ba-ac1c-bfb66d1b179a

```
{
    "operation": "deleteUser",
    "record": {
        "id": "mopan27443@cosaxu.com"
    }
}
```

```
{
    "message": "Internal server error"
}
```

**The user participates in at least one chat, i.e. has sent messages, so he can't be deleted.**

If such a user will be deleted, then the open questions are:
- Do we need to display the messages that were sent by this user?
- Do we need to display the name of the deleted user in the chat?

**Comment by k-tratseuski** [comment]
@billypilgrim88 we need to decide what to do with chat messages when we want to delete the user.
Do we need to update all user messages with null value for user or should we delete all the messages from user?

**Comment by billypilgrim88** [comment]
Delete all the messages from the user.

**Comment by k-tratseuski** [comment]
Ok

**Comment by k-tratseuski** [comment]
@TonyaUkrainets done, ready for testing

**Comment by TonyaUkrainets** [comment]
fixed
