### ISSUE TITLE
SSN conversion

### ISSUE THREAD

**Issue by TonyaUkrainets** [CarSnoop-Inc/carsnoop-issues#189]
User cadinek689@otodir.com

User added SSN as `"123456789"`
![image](https://user-images.githubusercontent.com/112691890/219049426-6e95fa9a-6694-46b2-abf6-97bfaa78e225.png)

BE returned SSN as `"15e2b0d3c33891ebb0f1ef609ec419420c20e320ce94c65fbc8c3312448eb225"`
![image](https://user-images.githubusercontent.com/112691890/219049373-4823023b-6e2b-44d7-ac54-a4ce7f8d515b.png)

**Comment by k-tratseuski** [comment]
@TonyaUkrainets done, ready for testing

**Comment by TonyaUkrainets** [comment]
fixed
![image](https://user-images.githubusercontent.com/112691890/219080476-0bfa1c44-a8ca-46ee-898e-62b0733deb4c.png)
