### ISSUE TITLE
WEB: Payment API

### ISSUE THREAD

**Issue by reutenkoivan** [CarSnoop-Inc/carsnoop-issues#19]
## Behavior
We need to redirect the web application to the prefilled stripe checkout page. During this process, we need to create a session, which can be securely generated only on the server side of the system, also we need a session for checkout payment results when the `updatePayment` has been called.

### Request
```typescript
type PaymentRequest = {
  type: 'payment'
  transaction_id: string
  amount: number
  success_url: string
  cancel_url: string
}

type SubscriptionRequest = {
  type: 'subscription'
  amount: number
  success_url: string
  cancel_url: string
}

interface CreateCheckoutPaymentRequest {
  operation: 'createCheckoutPayment'
  record: PaymentRequest | SubscriptionRequest
}
```

### Response
```typescript
interface CreateCheckoutPaymentResponse {
  payment_url: string
  session_id: string
}
```

**Comment by jongilman8** [comment]
Done, check the new Postman.
