### ISSUE TITLE
Delete signed documents

### ISSUE THREAD

**Issue by TonyaUkrainets** [CarSnoop-Inc/carsnoop-issues#191]
If the contact details have been changed, then the CarSnoop Purchase Agreement is deleted and needs to be regenerated. But the Signed CarSnoop Purchase Agreement is not deleted if they were signed and downloaded.

https://carsnoopworkspace.slack.com/archives/C03HDAGPVNC/p1676479160231069

**Comment by k-tratseuski** [comment]
@TonyaUkrainets done, ready for testing

**Comment by TonyaUkrainets** [comment]
fixed
