### ISSUE TITLE
Subscriptions

### ISSUE THREAD

**Issue by billypilgrim88** [CarSnoop-Inc/carsnoop-issues#192]
For now, we need to disable subscriptions. Let's do the following:
1. Comment out checkSubscription and instead return a flat fee for buyer and seller. Let's make this fee an environment variable so we can change it as necessary. For now set the fee to $500 for buyer and $500 for seller.
2. Hide the subscription entry in the menu
3. For the buyer, their $500 deposit on the deal will be applied as their payment
4. For the seller, we need a payment checkout screen at the end of the process to complete the deal.

**Comment by k-tratseuski** [comment]
@billypilgrim88 
4. Do you mean we need ask to pay 500$ when the seller completes the contract? Since completing the deal is performed by buyer

**Comment by YunchytsK** [comment]
Based on call with Cole:
1. Disable the “Check Subscription” logic;
2. Hide the “Subscription” section only for the “Buyer” user type;
3. Once “Dealer” user type initiates to go to the “Subscription” section  - we have to display the modal window with text “Regarding pricing contact your CarSnoop representative, please”. And do not display info with possible subscription packages (free/small/medium/large).
Is it ok?

**Comment by k-tratseuski** [comment]
Added `DisableSubscriptions` env to dynamically enable/disable this logic
