### ISSUE TITLE
BE changes flow and Release policy

### ISSUE THREAD

**Issue by vitalik77795** [CarSnoop-Inc/carsnoop-issues#200]
Hello, John. We would like to share with you our **BE changes flow** and **Release policy**. So, could you, please, take a look at this issue? What do you think about these flows?

### **BE changes flow**	

1. Create an issue on GitHub.
2. Describe an issue requirements and formalize it.
3. BE developers fix the issue in **development** environment.
4. Notify team members that changes is done and **ready for testing**.
5. QA team test changes and notify about testing results.
6. If the problem is fixed and **ready for deployment.**
7. Deploy changes to production environment.
8. Developer should close an issue.

### **Release policy**

1. When both sides are ready for deployment release process could be started.
2. BE team **deploy** to development environment. 
3. FE team **deploy** build  to stage stand.
4. Notify QA team, that stage stand is **ready for testing**.
5. QA team provide testing on stage stand and notify about results.
6. If all test cases are passed, release is **ready for** production **deployment**.
7. Synchronize the time of BE and FE release(if it’s required).
8. **Deploy** changes on production stand.
9. QA team test changes on production and notify about testing results(if it’s possible).

### **How to release on FE**

**Pre-release(stable stand)**

1. Go to the [Releases page](https://github.com/CarSnoop-Inc/carsnoop-web/releases).
2. Click **Draft a new release**.
3. Click **Choose a tag**.
4. Start typing next release tag (for example - `release_0.15.0`).
5. Click **Generate release notes below**.
6. Choose **Set as a pre-release option**.
7. Click **Publish release**.
8. Your pre-release is ready for testing.
When new pre-release is published it triggers `pre-release.yml` workflow. During the workflow it:
-  creates new build then uploads the build to `carsnoop-webapp-test/releases/${{ release.tag_name }}` in S3
- creates new build then uploads the build to `carsnoop-webapp-test/` bucket in S3.
- starts integration tests.

**Release**

1. Go to the [Releases page](https://github.com/CarSnoop-Inc/carsnoop-web/releases).
2. **Choose the pre-release** you need to release.
3. Click on **Edit**(Pencil) icon.
4. Choose **Set as the latest release option**.
5. Click **Publish release**.
6. Your release is ready!!!

-  When new release is published it triggers release.yml workflow. During the workflow it:
- creates new build then uploads the build to carsnoop-webapp-production/releases/${{ release.tag_name }} in S3
- creates new build then uploads the build to carsnoop-webapp-production/ bucket in S3
- starts integration tests.

1. How to revert releases.
2. Navigate to the [Actions](https://github.com/CarSnoop-Inc/carsnoop-web/actions) tab.
3. Pick **Revert release** workflow on the right panel.
4. Click **Run workflow**.
5. In dropdown **Use workflow** from select the tag you want to revert to.
6. Click **Run workflow**.
7. That's it. In several minutes you will see target version of the app in the latest release link.

You can find more information about release process on [This page](https://docs.github.com/en/repositories/releasing-projects-on-github/managing-releases-in-a-repository) .

**Comment by billypilgrim88** [comment]
Yes, this looks good to me.
