### ISSUE TITLE
Invalid request broke receiving information via chat

### ISSUE THREAD

**Issue by TonyaUkrainets** [CarSnoop-Inc/carsnoop-issues#203]
During development, a message was sent with `content_type: "jpg"`, although `content_type: "image/jpg"` was expected in `createChatMessage`.

BE allowed sending a request with this parameter, but now getting information on chat / chats through methods `readChats` and `readChat` is completely broken.
Because we get an error:
![image](https://user-images.githubusercontent.com/112691890/224326575-603d0c7d-18dc-4042-b292-f67c69fe45a7.png)

Can we make it so that the backend does not allow sending data that it does not expect to see?
If the request contains correct data, then everything is OK. 
If at least one parameter in the request differs from the format that is expected, an error occurs.

**Comment by k-tratseuski** [comment]
@TonyaUkrainets @vitalik77795 please share the values

**Comment by k-tratseuski** [comment]
@scottwoodall I think that we need only to check that this field is a valid mime-type.

**Comment by k-tratseuski** [comment]
@scottwoodall yes, since now we don't use lambda envs anymore seems you need to fix config inside carsnoop layer
![image](https://user-images.githubusercontent.com/117080223/225128673-f489411b-0393-4b0e-a215-34fc39c5b8af.png)
Check the code in chatFunctions, there is a new function that provides AWS Secrets

**Comment by k-tratseuski** [comment]
@scottwoodall cool, yes, seems that it was related to the same account, thanks a lot

**Comment by TonyaUkrainets** [comment]
fixed
