### ISSUE TITLE
readAccount returns Internal Server Error

### ISSUE THREAD

**Issue by vitalik77795** [CarSnoop-Inc/carsnoop-issues#204]
We have a problem with readAccount API for users:
tomij38217@luxeic.com
12345678
![image](https://user-images.githubusercontent.com/110094517/224327432-0bd55f4e-a8dd-4d4a-b7db-67cc5e51e1fc.png)
yebah35965@gpipes.com
12345678
![image](https://user-images.githubusercontent.com/110094517/224328207-30398b35-50e4-4b95-958b-6bc173af9c65.png)
![image](https://user-images.githubusercontent.com/110094517/224328358-093798a0-b215-46cb-8f25-19384a8800a5.png)

**Comment by k-tratseuski** [comment]
@vitalik77795 Fixed, now the error is handled correctly. Since stripe env are not set

**Comment by TonyaUkrainets** [comment]
fixed
