### ISSUE TITLE
Fix bug with stage env

### ISSUE THREAD

**Issue by k-tratseuski** [CarSnoop-Inc/carsnoop-issues#205]
New flow with stage env is not working. That's why mailings, some endpoints are not working

**Comment by billypilgrim88** [comment]
Full list of issues here: https://docs.google.com/spreadsheets/d/1TTtgRO_LwoolS4uVobeMPsRPLKrAR9c_ZwloOs6x9y8/edit?pli=1#gid=131711445

**Comment by k-tratseuski** [comment]
@billypilgrim88 I've commented Scott about chat functions since os.environ is used iside carsnoop layer (where is the main logic of chat is located). So he needs to fix that somehow

**Comment by k-tratseuski** [comment]
That part is fixed
