### ISSUE TITLE
FYI. Frequency of requests

### ISSUE THREAD

**Issue by TonyaUkrainets** [CarSnoop-Inc/carsnoop-issues#209]
We have two requests in chats that are called with some frequency:
readChats - 30sec
readChatMessages - 20 sec

So, on the web these periods are placed in the secrets of the repository.
But on mobile - hardcoded (the approach that is applied on the web is not suitable for mobile)

JFYI
If it is necessary to change the frequency, this will need to be done in two different places

**Comment by billypilgrim88** [comment]
@ramziddinAndersen - on mobile, how are we handling other environment variables like API endpoints? Can we not handle this the same way?
