### ISSUE TITLE
Closed Request with open Transaction

### ISSUE THREAD

**Issue by TonyaUkrainets** [CarSnoop-Inc/carsnoop-issues#21]
request - 91d4f1ca-5ec5-4bd5-bced-54b7118b26db
transaction 1 - 74e858a3-79e5-4df6-8951-cbbd0fa7f8c3
transaction 2 - 2c2a36c1-3902-47e5-a0b2-43d5e663c85d

Transaction 1 is Declined
![image](https://user-images.githubusercontent.com/112691890/203085863-d6307aaa-193e-4b34-9a0d-4f6fe3bec414.png)

Transaction 2 is Requested
![image](https://user-images.githubusercontent.com/112691890/203085995-ffcedf96-3392-494d-9fe6-80f51a476769.png)

Request should be Open, but it`s Closed
![image](https://user-images.githubusercontent.com/112691890/203086234-def48dce-75b8-4a9a-a41e-4c9c8fdb171b.png)

**Comment by TonyaUkrainets** [comment]
+ 
Trade in vehicle 525fea59-24a8-4f14-8fce-259c9c3bca5f should be in In Request status (there is one opened transaction)
But it has Available status
![image](https://user-images.githubusercontent.com/112691890/203087138-0488ed27-7c67-42f3-9e55-4aafe21c7292.png)

**Comment by k-tratseuski** [comment]
@TonyaUkrainets done, ready for testing

**Comment by TonyaUkrainets** [comment]
fixed
