### ISSUE TITLE
Add Vehicle: Cannot Proceed if Exterior or Interior Colors Drop Down Has No Values

### ISSUE THREAD

**Issue by billypilgrim88** [CarSnoop-Inc/carsnoop-issues#212]
In some cases, we will not have a list of drop down values for exterior or interior colors. For example, this 2020 Cadillac Escalade Platinum below has no values for interior color. The user cannot type in a color nor can the user proceed to save the new vehicle. We need to allow the user to type in a value for exterior and interior color that is different from the drop down list:

![1](https://user-images.githubusercontent.com/106979142/228844993-9b0b0245-93c0-4c02-af10-7bde2743bac3.PNG)
![2](https://user-images.githubusercontent.com/106979142/228845005-4f09929a-86e5-4b01-8403-38ffaba4faef.png)

**Comment by ssysoi** [comment]
we're on it

**Comment by vitalik77795** [comment]
@billypilgrim88 fixed. Issue can be closed
