### ISSUE TITLE
RunBuggy link stopped working

### ISSUE THREAD

**Issue by TonyaUkrainets** [CarSnoop-Inc/carsnoop-issues#220]
RunBuggy  returns a link, but when we click on it, we get a blank screen.
Before, it was transferred to RunBuggy and we could see the delivery status.

Example of link:
https://ng-staging.runbuggy.com/staging-green/spa-v2/#/external/order-statusorderId=54393776-cf34-47da-8f2a-25581764708b&token=eyJhbGciOiJSUzI1NiIsInR5cCI6IkpXVCJ9.eyJqdGkiOiJmNjE2MjhkNC00NGE1LTQ3NTAtYWQ2MS05MzI0Y2E4NDFmOWIiLCJpc3MiOiJodHRwczovL2FwcHMucnVuYnVnZ3kuY29tIiwiaWF0IjoxNjU4ODQ4MTExfQ.Nt0yIs7icOpU1HXxHSWEG75GNK90iKEIL_NjNpB0NcpgZ6Je04zXe36e5FqU5-GRkVSyvBZBcDV_al9lxiQNfTTlGb4VK6rkDIvK0g9yx_bbhXtmCzZ8yULwggnjJoqG1ho8yCGZ7GzAp6wPgQrC0c3HskSe8s7Ij8l5iViVWJmBugrWDwLQrsIfXLyKbN6dvBQ5A8al_0kejSFhGAI2xv7wc0-8n4cz2Oh35U9FGgL0UpxVu-H0R1HB2EEtHxklK3xHIkn_KcTJV_tMthd8mJeov3_RnoFlVoSu7DS7y3HaEVpAGnNd1Fn2QsPV5FIYayju7yRkbtEmcbke4LTfNQ&sections=MAP,STATUS_BAR,TIMELINE

**Comment by billypilgrim88** [comment]
No changes have been made to the RunBuggy logic in several months. This could be an issue on their side, let's monitor and see if it resolves itself.
