### ISSUE TITLE
Cannot Upload PDF Documents to Contracts in Web Version

### ISSUE THREAD

**Issue by billypilgrim88** [CarSnoop-Inc/carsnoop-issues#230]
PDF documents are greyed out when trying to upload to a contract:

<img width="1798" alt="Screenshot 2023-04-12 at 3 57 58 PM" src="https://user-images.githubusercontent.com/106979142/231570739-a4b75775-b531-4ac9-af04-c89bc64cd720.png">

**Comment by ssysoi** [comment]
fixed and tested on mac. deployed on prod. env

**Comment by billypilgrim88** [comment]
Looks good.
