### ISSUE TITLE
Create mechanism to have common makes and models

### ISSUE THREAD

**Issue by k-tratseuski** [CarSnoop-Inc/carsnoop-issues#232]
We've faced with some issues when scrapped car make and model could differ from our data for make, model comboboxes. That's why we need to think how to align all makes and models. Check the examples below
![image](https://user-images.githubusercontent.com/117080223/232435679-75480948-c59c-4196-8e58-5997cf71015f.png)
![image](https://user-images.githubusercontent.com/117080223/232435716-d703e237-c09d-4299-ba2e-e8f461c48e34.png)
![image](https://user-images.githubusercontent.com/117080223/232438468-35832fa2-9506-4978-aae1-2a1df64cec10.png)

**Comment by billypilgrim88** [comment]
Updated database with the following: update vehicles set make = 'Mercedes-Benz' where make = 'Mercedes Benz';

I will research what to do about Mini.
