### ISSUE TITLE
Request Will Not Display If retail_value = NULL

### ISSUE THREAD

**Issue by billypilgrim88** [CarSnoop-Inc/carsnoop-issues#238]
Check out: https://shop.carsnoop.com/deals/buy/68bbf061-a335-4e2b-a590-c3c6e2450fe9

readTransaction is successful, but the screen goes white:

<img width="836" alt="Screenshot 2023-04-21 at 1 34 09 PM" src="https://user-images.githubusercontent.com/106979142/233699534-9d03743f-306f-4457-a7c3-d0ef97f9d3e5.png">

**Comment by billypilgrim88** [comment]
After changing the retail_value in the database, the request displayed:

<img width="977" alt="Screenshot 2023-04-21 at 2 29 29 PM" src="https://user-images.githubusercontent.com/106979142/233709880-93ffdc03-a0cc-49c5-8fe2-38a88576fce9.png">

**Comment by ssysoi** [comment]
on it

**Comment by k-tratseuski** [comment]
@billypilgrim88 The issue is that we can't scrape the price from that car. So we need to decide what should we do with such vehicles. Should we ignore them (not populate the db) or should we set 0 price or should we leave it as null and skip for searching in the requests

**Comment by pozernishku** [comment]
Done in https://github.com/CarSnoop-Inc/carsnoop-backend/pull/46

**Comment by pozernishku** [comment]
Updated DB as well

**Comment by pozernishku** [comment]
Deployed
