### ISSUE TITLE
Wrong status for Transaction if Offer is created

### ISSUE THREAD

**Issue by TonyaUkrainets** [CarSnoop-Inc/carsnoop-issues#24]
request - 58f865e7-0981-4d2a-981d-e241586db13b
offer for 1st transaction - 6d628279-49af-4a45-b61b-5426532dfac9
transaction 1 - 075839da-7be9-47e5-9223-e8c96e374e1f 
transaction 2 - 617b8d31-bc8d-405e-ae5e-60271a51e435
--------------------
The request has 2 transactions.
The offer is created for the 1st transaction.

**Expected result:** the second transaction moved to the Request Cancelled status

**Actual result:** the second transaction moved to the Request Declined status
![image](https://user-images.githubusercontent.com/112691890/203128314-da1b3976-d5a5-4477-8c36-6b32aeecf36f.png)

**Comment by k-tratseuski** [comment]
@TonyaUkrainets should been fixed since I've refactored createOffer

**Comment by TonyaUkrainets** [comment]
still doesn`t work

request - 501a686f-599a-4a4c-b2c7-f5c844c20147
offer for 1st transaction - 46b3bdf5-b36d-4b56-bad0-cb30c39971d7
transaction 1 - b577d52d-a4a9-46fe-8583-0e0e74f9dcff
![image](https://user-images.githubusercontent.com/112691890/205352579-54c410ef-6ac8-4663-99b8-fbf805c10d59.png)

transaction 2 - 4faac0e3-d8d2-4e3c-94dd-f379d8b00f0f
![image](https://user-images.githubusercontent.com/112691890/205352689-1e0797ec-f01a-4417-bc13-dc2703322a16.png)
