### ISSUE TITLE
Scrapers. Postgres OperationalError: too many clients already

### ISSUE THREAD

**Issue by pozernishku** [CarSnoop-Inc/carsnoop-issues#240]
During the scraping almost simultaneously many `lambda_handler()` are launched in the body of which, using `psycopg2`, it is done: `connection = create_connection(secrets)`, which causes a problem on screenshot bellow. Also, there is a `finally` block in the code where the connection is closed: `connection.close()` (there is no issue with not closed connections). But we still need more connections for scraping process. To do this, one option here would be to use an [RDS proxy](https://us-east-2.console.aws.amazon.com/rds/home?region=us-east-2#proxies:) which cost some additional price. Would that be ok for you?
@billypilgrim88 

FYI @ssysoi 

<img width="1348" alt="Снимок экрана 2023-04-25 в 16 03 04" src="https://user-images.githubusercontent.com/14317371/234294093-e65029f7-6fec-4e24-b5fa-7a7b7ef256f3.png">

**Comment by billypilgrim88** [comment]
Sure, please proceed with RDS proxy.

**Comment by pozernishku** [comment]
Postponed with RDS proxy (for now) as we found that the root cause for this "too many clients already" issue is the size of DB being to large for `db.t3.micro`
