### ISSUE TITLE
readRequests timeout error

### ISSUE THREAD

**Issue by k-tratseuski** [CarSnoop-Inc/carsnoop-issues#242]
If the account has quite many open requests, `readRequests` returns a timeout error. It happens because of `calculateDistances`. We trigger this for each request. Usually it takes more than 4 seconds per each call. Lambda has 30sec timeout. That's why it's failing. We have 2 options:
1) to store the distance in the DB (Probably on the creating request step)
2) to remove the distance from list views (the fastest and simplest solution)
![image](https://user-images.githubusercontent.com/117080223/234860535-a21cc48c-e092-4260-922c-be611e198fe4.png)

**Comment by ssysoi** [comment]
when going to Deals->Buying->Requests readRequests is called
and inside it, calculateDistances is called to calculate the distance away for each car
![image](https://user-images.githubusercontent.com/56298532/235086684-1a23bc64-06a1-40f7-93f8-ccb9e948e9af.png)

**Comment by k-tratseuski** [comment]
@billypilgrim88 or 3 option: to move logic to FE. When user clicks arrow to show the list of transactions. FE triggers calculateDistances for some specific zipcodes for concrete request. In this case we will not trigger calculateDistances if it's not needed. Timeout error is not an issue anymore. But this needs some changes on FE and mobile side.

**Comment by k-tratseuski** [comment]
@billypilgrim88 The fastest and simplest solution is to remove this field from list views

**Comment by ssysoi** [comment]
![image](https://user-images.githubusercontent.com/56298532/235721085-c911c65c-9eb6-468f-8db0-0eda6c6a55fc.png)
