### ISSUE TITLE
Show dealerships an inventory item before they have an account

### ISSUE THREAD

**Issue by vitalik77795** [CarSnoop-Inc/carsnoop-issues#245]
@billypilgrim88, we've investigated how to show an inventory item(vehicle page) without registration and decided that the easiest way will be to create a new page  and show all information there. We'll skip readUser, readAccout API calls there. But we need to do changes from BE side to remove session checking from **readVehicle** and **readCarfaxLink** to read all necessary information. Path to the page could be https://shop-test.carsnoop.com/public/vehicles/id for example.
 What do you think about this? Is it ok?
 And I have some questions for you:
 - Are you going to expose page only to show it to dealerships? Or this page will be used to share between users?
 - How are you going to get link to some particular vehicle? Could you do it manually, or should we add some button to share public link to particular vehicle?

**Comment by billypilgrim88** [comment]
Yes, that solution will work. The page will be visible to anyone who wants to view the vehicle. We will manually create the link.

**Comment by vitalik77795** [comment]
@billypilgrim88 the page is ready. So, you could test on https://shop.carsnoop.com/public/vehicles/:vehicleId .
