### ISSUE TITLE
Mobile: Select Deliver To Address Automatically

### ISSUE THREAD

**Issue by billypilgrim88** [CarSnoop-Inc/carsnoop-issues#248]
Right now if you don't select a Deliver To address on the Home Screen, searchInventory returns no results. Instead, automatically select the first address on the user's account similar to the way the web version works:

![image](https://user-images.githubusercontent.com/106979142/236865116-f751e28f-2fe2-4301-b898-fc654291cf64.png)

**Comment by TonyaUkrainets** [comment]
Could you update the app and double check?

**Comment by billypilgrim88** [comment]
Looks good.
