### ISSUE TITLE
Mobile: Address Bug on Garage Screen

### ISSUE THREAD

**Issue by billypilgrim88** [CarSnoop-Inc/carsnoop-issues#249]
The addresses are blank on the Garage screen so the user cannot see the vehicles they have uploaded:

![image](https://user-images.githubusercontent.com/106979142/236865699-ef69b6db-2e42-441b-95e8-1bba423f2dfb.png)

**Comment by TonyaUkrainets** [comment]
Could you update the app and double check?

**Comment by billypilgrim88** [comment]
Looks good.
