### ISSUE TITLE
Status is changed for Canceled Transaction 

### ISSUE THREAD

**Issue by TonyaUkrainets** [CarSnoop-Inc/carsnoop-issues#25]
request - 5281e6a8-eb72-41ce-ba3d-ff776fd7a3e1
vehicle 1 - d291107d-4622-40aa-b83b-e8131fbc84dd
vehicle 2 - 207aa2b9-e210-41b4-a925-40ffbb523e1d
trade In - b92e36e8-a830-4b3d-925a-09edab8542f5
transaction 1 - 79726f0c-7442-46e1-803d-56d3f27c571e
transaction 2 - 947b5428-0530-48c4-bfea-ec5b4afe6e0b
----------------------------------------
Request has 2 transactions.
1st Transaction was Cancelled
![image](https://user-images.githubusercontent.com/112691890/203261105-6038c421-07a6-4ff4-8587-6f718cea4bbb.png)

Then 2nd Transaction was Expired
![image](https://user-images.githubusercontent.com/112691890/203261281-933bc502-542a-44b1-a7a3-1c0df6ea95ac.png)

Then 1st Transaction has status "Request Expired", but it should be still Request Cancelled
![image](https://user-images.githubusercontent.com/112691890/203261623-0f4af67d-6884-4f31-a32a-0e69df5a6815.png)

**Comment by k-tratseuski** [comment]
@TonyaUkrainets it's needed to check if it's reproducible since logic for cancelling changed

**Comment by TonyaUkrainets** [comment]
request - f007a339-2e92-43f5-ae12-9009ad7e3ed6 - Closed
![image](https://user-images.githubusercontent.com/112691890/205873587-5dc09829-1b05-4923-a64d-a8048ab29104.png)

vehicle 1 - 5b8e9de4-1555-48e0-b569-8b7a51b55c20 - Avaliable
![image](https://user-images.githubusercontent.com/112691890/205873664-dba42e56-e6a6-4000-a79c-2f48d3e5761c.png)

vehicle 2 - f317235e-28c8-43aa-805c-e619ddf3e844 - Available
![image](https://user-images.githubusercontent.com/112691890/205873756-d4445750-bb60-496b-af51-6ace45aa4155.png)

transaction 1  - 63a4a6cf-1b79-4248-a220-bbe9749511be - should be Request Cancelled, bit still Request Expired
![image](https://user-images.githubusercontent.com/112691890/205873913-350fb75b-3cff-42dc-8ba0-0b36d723f33d.png)

transaction 2  - 300d55f5-c89c-422a-ad55-50b22581b9e5
![image](https://user-images.githubusercontent.com/112691890/205873984-704016b9-a5e1-44e8-a5f3-7f19150cafad.png)

trade in - 07162f5b-61de-48af-a655-05b97b670bd0 - Available
![image](https://user-images.githubusercontent.com/112691890/205874075-e75c555e-89a8-4bce-bd9a-7d98c2de618b.png)

**Comment by k-tratseuski** [comment]
@TonyaUkrainets didn't get you

**Comment by k-tratseuski** [comment]
@TonyaUkrainets, ready for testing

**Comment by TonyaUkrainets** [comment]
fixed
request - e419dd76-7043-4c31-a95b-7c16bd237e7a
vehicle 1 - aabf4824-0236-400f-b8ca-7b3f1721374e - Avaliable
vehicle 2 - fc75bb21-42f9-4f17-84d4-96a29ae6efe7
transaction 1  - 02129084-6006-4f76-b7e6-b5116d3af5a6 - Request Cancelled
![image](https://user-images.githubusercontent.com/112691890/206671650-b4001c56-b832-49a6-8077-476a569ec1ab.png)

transaction 2  - f5627c9f-fa4e-4e17-be76-e8470768b5c9
trade in - 05dd9b7f-08c7-40b3-b47b-b5c15bce2799
