### ISSUE TITLE
Mobile: Add Save Button to Photos Tab on Edit Vehicle

### ISSUE THREAD

**Issue by billypilgrim88** [CarSnoop-Inc/carsnoop-issues#250]
Although the user can click back on the Details tab and click Save, it is a very confusing navigation. We need to add the Save button to the Photos tab so that they think they have finished editing the vehicle (even though the photos have already been saved):
![image](https://user-images.githubusercontent.com/106979142/236867327-d4129273-965d-4494-961f-72c0cd8b6229.jpeg)

**Comment by TonyaUkrainets** [comment]
We will add a standard Save button at the bottom of the page
Edit Mode will be closed by clicking on it and the updated Detail page of vehicle will be displayed

**Comment by TonyaUkrainets** [comment]
Button added.
It doesn't show up by default.
Appears only after adding or deleting a photo
Could you update the app and double check if there are any comments?
