### ISSUE TITLE
Statuses for objects if 2 vehicle in 2 requests

### ISSUE THREAD

**Issue by TonyaUkrainets** [CarSnoop-Inc/carsnoop-issues#26]
1. Request Tonya has:
    Vehicle Honda
    Vehicle Audi
    Trade In Opel

2. Request Kostya has:
    Vehicle Honda (the same as in Tonya's Request)
    Vehicle Audi (the same as in Tonya's Request)
    Trade In BMW

3. Offer created for Tonya.Honda Vehicle

4. How it should be:

Request Tonya - Closed
Transaction Tonya.Honda - Offered
Vehicle Tonya.Honda - Offered
Trade In Tonya.Opel - In Offer
Transaction Tonya.Audi - Request Declined
Vehicle Tonya.Audi - Requested

Request Kostya - Open
Transaction Kostya.Honda - Request Cancelled
Vehicle Kostya.Honda - Offered
Trade In Kostya.BMW - In Request
Transaction Kostya.Audi - Requested
Vehicle Kostya.Audi - Requested

![image](https://user-images.githubusercontent.com/112691890/203308284-30815e1f-6ed9-4e9d-8647-33f8d58de9d3.png)

**Comment by k-tratseuski** [comment]
@TonyaUkrainets done, ready for testing

**Comment by TonyaUkrainets** [comment]
fixed
Request Tonya - Closed
e1ae4fc0-9539-4559-ba74-1967b5c5d3a2
![image](https://user-images.githubusercontent.com/112691890/204522843-28d59458-c831-441f-b065-637c67089d86.png)

Transaction Tonya.Honda - Offered
c9e25fdf-f7f2-43b5-9494-dd2ae46b855a
![image](https://user-images.githubusercontent.com/112691890/204522952-99bb0dcd-e7cc-4c16-bb6d-30b10d10cec2.png)

Vehicle Tonya.Honda - Offered
96946059-d8c3-4c76-b146-1646b741b255
![image](https://user-images.githubusercontent.com/112691890/204523070-f0679d22-81bd-4f45-9bb8-c630a43480f6.png)

Trade In Tonya.Opel - In Offer
aeb7cc55-63b6-4383-8f92-0ea297918cf1
![image](https://user-images.githubusercontent.com/112691890/204523146-797a8e5a-d8cd-43d6-97b3-f2b044fde0a2.png)

Transaction Tonya.Audi - Request Declined
44259b08-5eb0-4d65-910f-6044ef1a2805
![image](https://user-images.githubusercontent.com/112691890/204523250-d4a60d28-ffd2-46c7-8400-c78c495e00a6.png)

Vehicle Tonya.Audi - Requested
5e1da9de-502e-400b-ac12-140264e59c3a
![image](https://user-images.githubusercontent.com/112691890/204523346-43bce168-3bae-4bd7-a38e-c6c5312b11c5.png)
-----------------------------------------
Request Kostya - Open
3f363b12-c674-4f5e-a5bc-d8fd0b59391b
![image](https://user-images.githubusercontent.com/112691890/204523488-5cddb76f-38d8-410e-b27e-533bf8dcc218.png)

Transaction Kostya.Honda - Request Cancelled
80915d5e-e945-45fe-a64f-b9f585b6b118
![image](https://user-images.githubusercontent.com/112691890/204523659-37c84b74-9f15-4cb1-9c2f-86f2eee45782.png)

Vehicle Kostya.Honda - Offered
96946059-d8c3-4c76-b146-1646b741b255
![image](https://user-images.githubusercontent.com/112691890/204523760-f4dee4c2-8adf-4452-a66a-052e43b277f3.png)

Trade In Kostya.BMW - In Request
41818560-06c4-471c-8310-5fd98a146fc1
![image](https://user-images.githubusercontent.com/112691890/204523850-ff1f6783-491d-43c3-8110-f6ef480511c5.png)

Transaction Kostya.Audi - Requested
19fffa9d-aa73-4627-9566-b7823c99212f
![image](https://user-images.githubusercontent.com/112691890/204523938-a3dadfca-ba5b-4e30-903c-336eda04570b.png)

Vehicle Kostya.Audi - Requested
5e1da9de-502e-400b-ac12-140264e59c3a
![image](https://user-images.githubusercontent.com/112691890/204524035-881af257-2021-40c6-88f6-bf2fb7500e6f.png)
