### ISSUE TITLE
Remove Smart 1 Marketing from Partner Access in Facebook

### ISSUE THREAD

**Issue by wehrlock** [CarSnoop-Inc/carsnoop-issues#262]
![Image](https://github.com/CarSnoop-Inc/carsnoop-issues/assets/381164/53ad4801-658f-4ec0-865d-450bb9953640)

**Comment by wehrlock** [comment]
https://www.facebook.com/Smart1Marketing

**Comment by billypilgrim88** [comment]
Fixed.
