### ISSUE TITLE
WEB: Payment API (confirmPayment method)

### ISSUE THREAD

**Issue by Skalapendra69** [CarSnoop-Inc/carsnoop-issues#27]
## Behavior
We need additional API for deposit payment confirmation.
When user returns back from Stripe we have to notify our backend that the user paid the deposit.
### Request
```typescript
interface ConfirmPaymentRequest {
  operation: 'confirmPayment'
  record: {
    session_id: string,
    transaction_id: string
  }
}
```
### Response
```typescript
interface ConfirmPaymentResponse {
  status: 'success' | 'failed'
}
```

The main idea is **let the backend know** that the **user has paid** so it can using _session_id_ go to **Stripe** to **check if it's really paid** and  modify the **contract** **status**

**Comment by jongilman8** [comment]
Done, call confirmPayment with the following payload:

{
    "operation": "confirmPayment",
    "record": {
        "session_id": "cs_test_a1x5VltQvILw4eXXwmHTvbFPaUNAaqj9ddUkHOBbJzBHya3CymOFXMvTFQ",
        "transaction_id": "00db8ed2-8117-49ab-807d-9b9d1db3a4f1"
    }
}
