### ISSUE TITLE
Remove Down Payment to Accept Offer

### ISSUE THREAD

**Issue by wehrlock** [CarSnoop-Inc/carsnoop-issues#271]
# Remove Down Payment to Accept Offer

## Research

- Found during #267 

## Current Workaround
- Click Accept Offer and initiate Stripe session
- Change **payment_reference** field in **payments** table to **MANUAL**
- Call createContract API with Postman (additional_buyer set to "", need to allow missing buyer)

### carsnoop-backend

- [x] https://github.com/CarSnoop-Inc/carsnoop-issues/issues/279
  Remove hardcoded append of $500 deposit to offer price components in the createContract endpoint

### carsnoop-web

- [x] Remove reference to deposit on Seller Offer Created page
- [x] Remove deposit microform on Accept Offer page
- [x] Remove reference to deposit on Payment Result page after Accept Offer
- [x] Hide Deposit line item when not exists in Offer Details section

### carsnoop-mobile

- [x] https://github.com/CarSnoop-Inc/carsnoop-mobile/issues/420
  - [x] Remove reference to deposit on Seller Offer Created page
  - [x] Remove deposit microform on Accept Offer page
  - [x] Remove reference to deposit on Payment Result page after Accept Offer
  - [x] Hide Deposit line item when not exists in Offer Details section

**Comment by billypilgrim88** [comment]
Short term workaround has been implemented. When the user click Continue with Deposit, the deposit process is bypassed and the contract is created. @wehrlock - it would be nice it we could:

1. Hide section 3 with the deposit information
2. Change the text on the button from "Continue with Deposit" to "Continue"

<img width="1837" alt="Screenshot 2023-06-28 at 2 24 28 PM" src="https://github.com/CarSnoop-Inc/carsnoop-issues/assets/106979142/e467f55a-61bd-4927-a768-a2caec45e7cf">

**Comment by wehrlock** [comment]
# Tracked Tasks

## carsnoop-backend

- [ ] Remove hardcoded append of $500 deposit to offer price components in the createContract endpoint

## carsnoop-web

- [ ] Remove reference to deposit on Seller Offer Created page
- [ ] Remove deposit microform on Accept Offer page
- [ ] Remove reference to deposit on Payment Result page after Accept Offer
- [ ] Hide Deposit line item when not exists in Offer Details section

## carsnoop-mobile

- [ ] Remove reference to deposit on Seller Offer Created page
- [ ] Remove deposit microform on Accept Offer page
- [ ] Remove reference to deposit on Payment Result page after Accept Offer
- [ ] Hide Deposit line item when not exists in Offer Details section
