### ISSUE TITLE
SSL on root domain

### ISSUE THREAD

**Issue by wehrlock** [CarSnoop-Inc/carsnoop-issues#274]
SSL Certificate should be on root domain: carsnoop.com. (not on test.carsnoop.com)

![Image](https://user-images.githubusercontent.com/381164/240711840-cc08e6d7-5f73-4b5d-86fb-6fcba023323c.png)

![Image](https://user-images.githubusercontent.com/381164/240711850-0d223fe5-f585-4d54-acaf-a16ca735ed53.png)

![Image](https://user-images.githubusercontent.com/381164/249517991-030674e3-6a85-4ee1-b876-1048a3e3a267.png)

**Comment by billypilgrim88** [comment]
Fixed.
