### ISSUE TITLE
Delayed Start to Lambda Functions 

### ISSUE THREAD

**Issue by billypilgrim88** [CarSnoop-Inc/carsnoop-issues#276]
Functions appear to run slowly due to the cold start feature in Lambda. Need to speed them up.

**Comment by wehrlock** [comment]
# carsnoop-backend tracked issue

- [ ] https://github.com/CarSnoop-Inc/carsnoop-backend/issues/82

**Comment by wehrlock** [comment]
✅ Provisioned 10 concurrent lambdas for **databaseFunctions** lambda, since that is the primary synchronous lambda that the frontend user interface is dependent on for displaying a page.
