### ISSUE TITLE
Final Payment Method Should Default to Check Instead of Stripe

### ISSUE THREAD

**Issue by billypilgrim88** [CarSnoop-Inc/carsnoop-issues#278]
# Tracked tasks

## Web

- [x] https://github.com/CarSnoop-Inc/carsnoop-web/issues/1004

## Mobile

- [x] https://github.com/CarSnoop-Inc/carsnoop-mobile/issues/419

**Comment by wehrlock** [comment]
[8940b7fac373a3b91036f2a07dda3ff31dcd201f](https://github.com/CarSnoop-Inc/carsnoop-web/commit/8940b7fac373a3b91036f2a07dda3ff31dcd201f)

**Comment by wehrlock** [comment]
# Tracked tasks

## Web

- [ ] https://github.com/CarSnoop-Inc/carsnoop-web/issues/1004

## Mobile

- [ ] https://github.com/CarSnoop-Inc/carsnoop-mobile/issues/419
