### ISSUE TITLE
Need a completeShipment api to finalize the deal

### ISSUE THREAD

**Issue by YunchytsK** [CarSnoop-Inc/carsnoop-issues#29]
Need api to completeShipment: update transaction to "Delivered", trade in vehicle status to "Delivered", update requested vehicle to "Delivered".

on UI transaction/vehicle/trade in vehicle will be displayed as "Delivered".

**Comment by jongilman8** [comment]
This would need to happen in databaseFunctions, reassigning to @k-tratseuski .

**Comment by k-tratseuski** [comment]
@YunchytsK, done, ready for testing
Example request body:
```json
{
    "operation": "completeShipment",
    "record": {
        "transaction_id": "b3db7787-fac4-40ab-865e-f7758da8fcfc"
    }
}
```
