### ISSUE TITLE
To add new object_type to createDocument to add Driver License

### ISSUE THREAD

**Issue by vitalik77795** [CarSnoop-Inc/carsnoop-issues#3]
Need to add new `object_type` to **createDocument** API to add driver license information.
And when user created document it should be available in **readUser** API for this user.
And document should be available in contract in the list of required documents as Primary Buyer's Drivers License if user is a buyer. 
![image](https://user-images.githubusercontent.com/110094517/202175103-7613c854-b41a-4e17-bce3-967bae94f094.png)

**Comment by k-tratseuski** [comment]
@vitalik77795 done, ready for testing

**Comment by k-tratseuski** [comment]
Now we have such obj inside `readTransaction`
```json
{
    "Name": "Primary Buyer's Drivers License",
    "Document_Id": "c3961b57-d9a3-437c-aa21-e0783f691a86",
    "link": "https://carsnoop.s3.us-east-2.amazonaws.com/c3961b57-d9a3-437c-aa21-e0783f691a86.png"
}
```
and `readUser` returns
```json
"driver_license_id": "c3961b57-d9a3-437c-aa21-e0783f691a86"
```

**Comment by k-tratseuski** [comment]
@vitalik77795 Updated `readUser` response. Now there is an obj
```json
"driver_license_file": {
        "id": "c3961b57-d9a3-437c-aa21-e0783f691a86",
        "type": "png",
        "created_on": "2022-11-21T09:44:05.092",
        "notes": "test notes for drivers license"
}
```
