### ISSUE TITLE
readShippingCost should return cost and distance

### ISSUE THREAD

**Issue by YunchytsK** [CarSnoop-Inc/carsnoop-issues#30]
1. readShippingCost should return cost and distance
2. if trade in vehicle exists readShippingCost should return total cost and total distance for delivery of both vehicles

**Comment by jongilman8** [comment]
It now returns distance. I'm working on 2, but the RunBuggy development environment is slow today so I may table this and work on something else.

**Comment by jongilman8** [comment]
Done.
