### ISSUE TITLE
Add ordering to readTransactions

### ISSUE THREAD

**Issue by TonyaUkrainets** [CarSnoop-Inc/carsnoop-issues#33]
Add the **deals** parameter to the request by which transactions will be sorted.

If parameter is **"deals":"in progress"** then ordering should be: “In progress” Deals should be ordered from oldest to newest based on _“Created on”_ date.

If parameter is **"deals":"completed"** then ordering should be: “Completed” Deals should be ordered from newest to oldest  based on _“Changed on”_ date.

**_+ start filling in the Changed on parameter_**

**Comment by reutenkoivan** [comment]
## Request structure proposal:

```typescript
type InProgressStatuses =
  | 'Offered'
  | 'Under Contract'
  | 'Awaiting Payment'
  | 'Shipping'

type CompletedStatuses =
  | 'Request Cancelled'
  | 'Request Declined'
  | 'Request Expired'
  | 'Offer Cancelled'
  | 'Offer Declined'
  | 'Offer Expired'
  | 'Contract Terminated'
  | 'Payment Failed'
  | 'Completed'

type ReadTransactionsRequest = {
  operation: 'readTransactions'
  record: {
    stock_number: string
    type: 'selling' | 'buying'
    sort?: 'ASC' | 'DESC'
    status?: Array<InProgressStatuses | CompletedStatuses>
  }
}
```

**Comment by k-tratseuski** [comment]
@reutenkoivan @vitalik77795 @ramziddinAndersen, @TonyaUkrainets  done, ready for testing
Request example:
```json
{
    "operation": "readTransactionsNew",
    "record": {
        "stock_number": "",
        "type": "buying",
        "status": "in_progress"
    }
}
```

**Comment by TonyaUkrainets** [comment]
fixed
