### ISSUE TITLE
Retail value of vehicle equal to the Vehicle price from Offer

### ISSUE THREAD

**Issue by TonyaUkrainets** [CarSnoop-Inc/carsnoop-issues#34]
According to requirement: update the Retail value of vehicle equal to the Vehicle price from Offer

Vehicle 176d62f8-d8dc-42a8-aae0-b132af4f01b7 has Retail value 36400
![image](https://user-images.githubusercontent.com/112691890/204021399-d2ff1a83-a6bc-4032-a991-cef9d8219811.png)

Offer is created with price as 1
![image](https://user-images.githubusercontent.com/112691890/204021517-fd3eb612-7136-492d-bfde-0323b359f945.png)

But the vehicle still has 36400 price
![image](https://user-images.githubusercontent.com/112691890/204021680-fe124487-ce37-4fc4-a7a0-92a7d04634b9.png)

**Comment by k-tratseuski** [comment]
@TonyaUkrainets done, ready for testing
