### ISSUE TITLE
removeTradeIn API clear only trade_in_vehicle field from transaction

### ISSUE THREAD

**Issue by vitalik77795** [CarSnoop-Inc/carsnoop-issues#35]
**removeTradeIn** clear only `trade_in_vehicle`, but not a `trade_in` field in transaction **(readTransaction)**. 
After **removeTradeIn** call with transaction id, I've got a response:
![image](https://user-images.githubusercontent.com/110094517/204029632-f03f6861-c9b7-4d0c-98b3-d3000ad48d3a.png)

And prop `trade_in` wasn't cleared.

**Comment by k-tratseuski** [comment]
@vitalik77795 ready for testing
