### ISSUE TITLE
Remove `seller`'s fields from `createContract` operation

### ISSUE THREAD

**Issue by Skalapendra69** [CarSnoop-Inc/carsnoop-issues#37]
Now `seller_legal_name` and `seller_legal_address` fields must be sent to `createContract`. But when frontend sends this request it doesn't have an info about seller. So it looks like it would be better if backend looks for the info by its own.

As far i know the shortest way to get that fields by frontend is:
 - `readTransaction` -> `offer.createdBy`
 - `readUser` by `createdBy` field to get `seller_legal_name` and `account_id`
 - `readAccount` by `account_id` to get addresses and get `seller_legal_address`

**Comment by Skalapendra69** [comment]
Related to https://github.com/CarSnoop-Inc/carsnoop-issues/issues/20

**Comment by k-tratseuski** [comment]
@Skalapendra69, done, check please the last comment in related issue
