### ISSUE TITLE
To add new notes(descripition) field to createDocument, readDocument API's

### ISSUE THREAD

**Issue by vitalik77795** [CarSnoop-Inc/carsnoop-issues#4]
Need to add new `notes(description)` field to **createDocument** and **updateDocument** API's.
It should have `string` type and can be empty string.

**Comment by k-tratseuski** [comment]
@jongilman8 We need to create a new str field `notes` for table `documents` to store file notes

**Comment by jongilman8** [comment]
Done.

**Comment by k-tratseuski** [comment]
@jongilman8 Cool, thx
