### ISSUE TITLE
Rework date format

### ISSUE THREAD

**Issue by TonyaUkrainets** [CarSnoop-Inc/carsnoop-issues#40]
If the date is in the format as in the screenshot, then we get a white screen on the tablet
![image](https://user-images.githubusercontent.com/112691890/204547976-eb937044-3167-42e5-afd7-e475b0b708bc.png)

Need format
![image](https://user-images.githubusercontent.com/112691890/204548977-8f90f75e-659c-48d8-835d-24723bc3e4de.png)

**Comment by k-tratseuski** [comment]
@TonyaUkrainets done

**Comment by TonyaUkrainets** [comment]
fixed
