### ISSUE TITLE
Add new fields to the table contracts

### ISSUE THREAD

**Issue by k-tratseuski** [CarSnoop-Inc/carsnoop-issues#41]
We've agreed to add new fields to the table contracts to split existing `additional_buyer_legal_address`, `seller_legal_address`, `buyer_legal_address`. In the end of the day we want to have something like `additional_buyer_address`, `additional_buyer_zip_code`, `additional_buyer_city`, `additional_buyer_state`, `seller_address`, `seller_zip_code` and etc. After adding new fields we need to migrate all the data to the new ones and delete old ones

**Comment by jongilman8** [comment]
Done, I will wait to delete the old fields until the code has been updated.

**Comment by jongilman8** [comment]
Old fields have been removed.
