### ISSUE TITLE
Documents: Make PDFs displayable in browsers

### ISSUE THREAD

**Issue by reutenkoivan** [CarSnoop-Inc/carsnoop-issues#42]
### Expected result
URL https://carsnoop.s3.us-east-2.amazonaws.com/4a6e8a05-be4e-4112-ac9c-3794ae87d59e.pdf should display like [THIS](http://idtc-icai.s3.amazonaws.com/download/3.%20Collated%20Suggestions%20submitted%20on%20Draft%20Rules.pdf)

### T&T:
In [THIS](https://stackoverflow.com/questions/71267084/display-pdf-file-stored-in-s3-bucket) issue there is advice to add 2 additional headers.

**Comment by k-tratseuski** [comment]
@reutenkoivan , done, [pdf](https://carsnoop.s3.us-east-2.amazonaws.com/4018a818-51da-44e0-ba05-54e453531929.pdf)
