### ISSUE TITLE
To add deposit to offer

### ISSUE THREAD

**Issue by vitalik77795** [CarSnoop-Inc/carsnoop-issues#44]
When deposit was confirmed(we make a call createContract API) we need to do:
1. Add to the current offer of transaction  to `price_components`  prop new item with name `'Deposit'` and amount `500`. Or it can be a new prop in offer. Now 500 is harcoded from UI persective.
2. Subtract 500 from `total_price` of this offer.

**Comment by k-tratseuski** [comment]
@vitalik77795 Done, ready for testing
