### ISSUE TITLE
Transaction entity | Integrate `previous_offer` field.

### ISSUE THREAD

**Issue by reutenkoivan** [CarSnoop-Inc/carsnoop-issues#45]
## Context
We have to display the previous state for offer details from business requirements. For this case, we need to extend the response from the **readTransaction** API by adding the `previous_offer` field.

### Create
1. set null for the `previous_offer` option.

### Update
1. pick the current state of the offer object from the DB
2. set aggregated data to the **previous_offer** field
3. set request data from the **updateOffer** API to `transaction.offer`

**Comment by k-tratseuski** [comment]
@reutenkoivan done
