### ISSUE TITLE
readModelYearTrim: trim field is require 

### ISSUE THREAD

**Issue by Skalapendra69** [CarSnoop-Inc/carsnoop-issues#5]
Sometimes a vehicles can have no trim so could you add an opportunity to send empty string as trim field value
![image](https://user-images.githubusercontent.com/50297089/201903807-572c086a-4684-4c05-b952-4900cfdc0ea2.png)

**Comment by TonyaUkrainets** [comment]
@jongilman8 Could you add some colors(exterior/interior) for any vehicle without Trim?
We would like to check the case when vehicle doesn't have Trim, but has colors and user can create such a car

**Comment by k-tratseuski** [comment]
@jongilman8 ?
