### ISSUE TITLE
seller_legal_name for Buyer Type

### ISSUE THREAD

**Issue by TonyaUkrainets** [CarSnoop-Inc/carsnoop-issues#53]
If `"is_dealer":true` -> `seller_legal_name` from `readAccount.name`
If `"is_dealer":false` -> `seller_legal_name` from `readUser.full_name`

**Comment by k-tratseuski** [comment]
@TonyaUkrainets done, ready for testing

**Comment by TonyaUkrainets** [comment]
fixed
