### ISSUE TITLE
Default exterior color, interior color, and trim should always default to Any*

### ISSUE THREAD

**Issue by jongilman8** [CarSnoop-Inc/carsnoop-issues#54]
Exterior color, interior color, and trim should always default to Any* from the beginning of the process:

<img width="2003" alt="Screen Shot 2022-12-06 at 10 55 03 AM" src="https://user-images.githubusercontent.com/106979142/205960420-07502600-a358-425c-b9c0-7539b66685c8.png">

**Comment by TonyaUkrainets** [comment]
fixed
