### ISSUE TITLE
Location in web version does not match design

### ISSUE THREAD

**Issue by jongilman8** [CarSnoop-Inc/carsnoop-issues#55]
In the web version, instead of State, City, Zip Code, it should be City, State, Zip Code:

<img width="641" alt="Screen Shot 2022-12-06 at 12 34 33 PM" src="https://user-images.githubusercontent.com/106979142/205982240-c8edf2ae-1c84-452c-ae0c-42df0dea9d4f.png">

**Comment by TonyaUkrainets** [comment]
fixed
