### ISSUE TITLE
Change the status name on BE side from "Completed" to "Delivered" 

### ISSUE THREAD

**Issue by YunchytsK** [CarSnoop-Inc/carsnoop-issues#58]
completeShipment: update transaction to "Delivered", trade in vehicle status to "Delivered", update requested vehicle to "Delivered".

relates to the issue https://github.com/CarSnoop-Inc/carsnoop-issues/issues/29

**Comment by k-tratseuski** [comment]
@YunchytsK, done, ready for testing
