### ISSUE TITLE
Avatar upload during registration process

### ISSUE THREAD

**Issue by Skalapendra69** [CarSnoop-Inc/carsnoop-issues#59]
Is needed to add `avatar` field to `registerUser` api. We will send link to the image like https://lh3.googleusercontent.com/a/AEdFTp4FNiU_M6cVMQXjTi8I3QPwCGqPJ-HWjsRE-KXo=s96-c

**Comment by k-tratseuski** [comment]
@Skalapendra69 done, ready for testing

**Comment by Skalapendra69** [comment]
![image](https://user-images.githubusercontent.com/50297089/207368492-b9135ad2-8635-4b83-bf28-df55485120be.png)
