### ISSUE TITLE
Steps for integrating 3party registration

### ISSUE THREAD

**Issue by reutenkoivan** [CarSnoop-Inc/carsnoop-issues#6]
1. Configurate S3 bucket for [static website hosting](https://docs.aws.amazon.com/AmazonS3/latest/userguide/HostingWebsiteOnS3Setup.html) (for LinkedIn)
2. Delivery the web-app with HTTPS protocol (configure domain with SSL certificate) (for Google and LinkedIn)

**Comment by jongilman8** [comment]
I think #1 is already done, the web version is running on an S3 bucket. Are you asking to add SSL and also domain in front of the bucket like https://portal-dev.carsnoop.com?

**Comment by reutenkoivan** [comment]
> Are you asking to add SSL and also domain in front of the bucket like https://**portal-dev.carsnoop.com**

Yes, could you deliver not root directory, but `s3://carsnoop-webapp/stable`?
> I think №1 is already done

I will check it, thank you

**Comment by jongilman8** [comment]
Done, you may need to check in incognito mode.

**Comment by Skalapendra69** [comment]
@jongilman8 Hello. I start checking login via Google on this page `https://portal-dev.carsnoop.com/` but it looks like i get old build of WEB app. Is it looking on `carsnoop-webapp/stable` or just contain copy of old build?

**Comment by jongilman8** [comment]
Probably need to clear you cache, it is pointed at stable:

<img width="1477" alt="Screen Shot 2022-12-09 at 2 49 52 PM" src="https://user-images.githubusercontent.com/106979142/206785322-a4b4ad7c-ff08-4c09-a2f3-7c7c6756ba50.png">

**Comment by Matroskin94** [comment]
@jongilman8 Hello! We have trouble with configuration of routing for our Single Page Application. When we trying to go to one of application pages not from the root page (excepting main page), it shows 404 page. It happens because it try to go to folder on static server (for example /deals), but it should always redirect to root index.html. It critically important issue, it partly blocks our QA. You can check this link for example:
http://carsnoop-webapp.s3-website.us-east-2.amazonaws.com/stable/deals
<img width="1792" alt="image" src="https://user-images.githubusercontent.com/15139637/208646756-140c3b53-753d-47d4-961e-a25651f164b4.png">

**Comment by jongilman8** [comment]
<img width="1023" alt="Screenshot 2022-12-20 at 10 03 39 AM" src="https://user-images.githubusercontent.com/106979142/208698051-99695a33-7541-4cea-a050-7c75f8e51385.png">

**Comment by reutenkoivan** [comment]
@jongilman8 I've found [a solution](https://stackoverflow.com/a/52343542) that, probably, can help us to resolve this problem

> @jongilman8 Hello! We have trouble with configuration of routing for our Single Page Application. When we trying to go to one of application pages not from the root page (excepting main page), it shows 404 page. It happens because it try to go to folder on static server (for example /deals), but it should always redirect to root index.html. It critically important issue, it partly blocks our QA.

**Comment by reutenkoivan** [comment]
Also, we have to make a custom build for addresses without a pathname in the URL (like **portal-dev.carsnoop.com**,) we already stored a new version for that in the `/pre-prod` folder.

That's why we ask you:
* Change the root project directory to `pre-prod/index.html`
* Check that static website hosting is enabled for this folder

**Comment by Skalapendra69** [comment]
@jongilman8 Here is an example how to setup hosting for apps with browser routing
https://dev.to/alexeyromanchenko/how-to-deploy-spa-as-a-static-website-using-aws-s3-1adg

**Comment by jongilman8** [comment]
It should be working now.

**Comment by Skalapendra69** [comment]
It's working a little strange. When we try get the app with any url like `...amazonaws.com/stable/vehicles/078b...` it returns files (.html, .js, .css) but the response still has 404 status code. Additionally it looks like that files aren't from `/stable` folder (it looks like old build)
![image](https://user-images.githubusercontent.com/50297089/209080160-4f708e69-5766-45d2-9033-aa468f8a20e9.png)

**Comment by k-tratseuski** [comment]
> Probably need to clear you cache, it is pointed at stable:
> 
> <img alt="Screen Shot 2022-12-09 at 2 49 52 PM" width="1477" src="https://user-images.githubusercontent.com/106979142/206785322-a4b4ad7c-ff08-4c09-a2f3-7c7c6756ba50.png">

@billypilgrim88, FYI: I've set up default root obj as `index.html` since @reutenkoivan has made some changes on FE side

**Comment by billypilgrim88** [comment]
Ok, can we close this one?

**Comment by k-tratseuski** [comment]
@billypilgrim88  sure
