### ISSUE TITLE
calculateDistances returns an error

### ISSUE THREAD

**Issue by TonyaUkrainets** [CarSnoop-Inc/carsnoop-issues#60]
Error comes when using 12345 Zip Code

Request body
```
{
    "operation": "calculateDistances",
    "record": {
        "origin": "12345",
        "destinations": [
            "46268",
            "60614"
        ]
    }
}
```
Response body
```
{
    "message": "Internal server error"
}
```

**Comment by k-tratseuski** [comment]
@jongilman8 Seems that you've triggered it with the wrong `zip_code`. There is no error with `46077`. But there is one with `12345 `
![image](https://user-images.githubusercontent.com/117080223/207016184-49f71e6b-bc8e-4bdf-97c1-31bb1a7c05bf.png)

**Comment by jongilman8** [comment]
Fixed, we now return an error if destination or origin zip code does not exist:

{
    "message": "Destination zip code 12345 does not exist."
}
