### ISSUE TITLE
Subtract deposit from total_price of offer.

### ISSUE THREAD

**Issue by vitalik77795** [CarSnoop-Inc/carsnoop-issues#62]
When we created a contract we need to subtruct deposit amount from` **total_price**` of offer: 
**Expected result:**
Deposit(500) will be subtrucred from `total_price` field of this offer(green)
**Actual Result:**
Deposit was substructed from offer's price_components with decription 'Vehicle Price'(red)
![image](https://user-images.githubusercontent.com/110094517/206735516-8a7b0587-6269-460d-958b-efd5d037580e.png)

**Comment by k-tratseuski** [comment]
@vitalik77795 done, ready for testing
