### ISSUE TITLE
Registration/Login through LinkedIn

### ISSUE THREAD

**Issue by Matroskin94** [CarSnoop-Inc/carsnoop-issues#66]
Trying to authenticate through LinkedIn, but always get error.
On web side all works fine, redirecting to LinkedIn page, getting code, and sending to our back-end, code should be correct.
`{
error: "invalid_request",
error_description:  "Unable to retrieve access token: appid/redirect uri/code verifier does not match authorization code. Or authorization code expired. Or external member binding exists"
}`
I'm testing it on localhost. Using this request **readLinkedInProfile**

**Comment by jongilman8** [comment]
I don't think you can test this on a localhost, the LinkedIn API requires HTTPS for the redirect URL.

**Comment by jongilman8** [comment]
It should be working now.

**Comment by k-tratseuski** [comment]
We've changed `redirect_uri` on the 3rd step here(https://learn.microsoft.com/en-us/linkedin/shared/authentication/authorization-code-flow?tabs=HTTPS1) in the code and now it's failing further.
So we are receiving such response
```json
{
    "serviceErrorCode": 100,
    "message": "Not enough permissions to access: GET /me",
    "status": 403
}
```
And another thing: we should be able to accept this `redirect_uri` as a parameter in `readLinkedInProfile`, since it could be dynamic

**Comment by billypilgrim88** [comment]
I need some specific details here, I'm not sure what you want me to do.

**Comment by k-tratseuski** [comment]
@billypilgrim88, on the step when we are trying to get linkedin account data (first name, last name, avatar) from https://api.linkedin.com/v2/me, we receive that response. The message tells us about some problem with permissions, but seems all that set up application account

**Comment by billypilgrim88** [comment]
I think you are using the wrong URL. I just tested and this works. The steps should be:

1. Call https://www.linkedin.com/oauth/v2/authorization?response_type=code&client_id=86b1ohabdfxnuy&redirect_uri=https://portal-dev.carsnoop.com/linkedin&scope=r_liteprofile%20r_emailaddress to retrieve the OAuth code
2. Pass the OAuth code to the readLinkedInProfile API
