### ISSUE TITLE
Make PDF accessible from the new S3 bucket

### ISSUE THREAD

**Issue by k-tratseuski** [CarSnoop-Inc/carsnoop-issues#68]
Currently uploaded pdfs are not accessible via the [link](https://carsnoop.s3.us-east-2.amazonaws.com/7dd49166-49f7-4de2-a7ab-51a3699a499d.pdf)
![image](https://user-images.githubusercontent.com/117080223/207626378-160206d0-f942-455e-a4a7-d49f503c4c7d.png)

**Comment by Ryanb58** [comment]
@k-tratseuski What API endpoint are you guys hitting to grab that documents URL?

**Comment by k-tratseuski** [comment]
> link

@Ryanb58

**Comment by k-tratseuski** [comment]
> Currently uploaded pdfs are not accessible via the [link](https://carsnoop.s3.us-east-2.amazonaws.com/7dd49166-49f7-4de2-a7ab-51a3699a499d.pdf) ![image](https://user-images.githubusercontent.com/117080223/207626378-160206d0-f942-455e-a4a7-d49f503c4c7d.png)

@Ryanb58

**Comment by k-tratseuski** [comment]
@Ryanb58 https://carsnoop.s3.us-east-2.amazonaws.com/7dd49166-49f7-4de2-a7ab-51a3699a499d.pdf

**Comment by ssysoi** [comment]
not actual
