### ISSUE TITLE
Vehicle in "For Sale" Status in "Under Contract" Transaction 

### ISSUE THREAD

**Issue by TonyaUkrainets** [CarSnoop-Inc/carsnoop-issues#69]
Transaction "fc0c7d35-2174-4bfe-984c-98171b2b5fc6" has "Under Contract" Status 
But Vehicle "4ffff98d-bb0b-42af-b60e-9dec9c80f713" in this transaction has "For Sale" Status

**Comment by k-tratseuski** [comment]
@TonyaUkrainets done, ready for testing
