### ISSUE TITLE
readTransaction trade in vehicle response is id not object and no needed fields

### ISSUE THREAD

**Issue by JSBmanD** [CarSnoop-Inc/carsnoop-issues#7]
readTransaction currently sends id of the vehicle not vehicle object.
as stated in that issue - https://github.com/CarSnoop-Inc/carsnoop-issues/issues/18 , there should be fields
    distance: string
    shipping_cost: number
That aren't present now

**Comment by k-tratseuski** [comment]
@JSBmanD, resolved, ready for testing
