### ISSUE TITLE
update shipping addresses API

### ISSUE THREAD

**Issue by Skalapendra69** [CarSnoop-Inc/carsnoop-issues#70]
[Epic description](https://wiki.andersenlab.com/pages/viewpage.action?spaceKey=CRSN&title=US11.4+To+edit+address+details)

We need an info about shipping addresses for transaction.

There should be two types of addresses:
 - Pickup address
 - Drop-off address

### Pickup address contains
 - Address Name: string
 - Street: string
 - Zip Code: string
 - City: string
 - State: string
 - Contact name: string
 - Contact number: string
 - Contact email: string
 - Notes: string

### Drop-off address contains
 - Address Name: string
 - Street: string
 - Zip Code: string
 - City: string
 - State: string
 - Contact name: string
 - Contact number: string
 - Contact email: string
 - Notes: string

So we need corresponding field are added into readTransaction response

**Comment by k-tratseuski** [comment]
@Skalapendra69, done, ready for testing
You could find it in `readTransaction` -> `contract` -> `pickup`/`drop_off` 
It has such structure
```json
{
  "address_name": "Home 1",
  "city": "Zionsville",
  "state": "IN",
  "street": "290 S 6th St",
  "zip_code": "46077",
  "contact_email": "test.client102@mail.ru",
  "contact_name": "Test User",
  "contact_number": "+13333333333"
}
```
