### ISSUE TITLE
Need API to complete the deal

### ISSUE THREAD

**Issue by AntonZakWork** [CarSnoop-Inc/carsnoop-issues#72]
Need new endpoint for completion of the deal: update transaction status to 'Delivered', update statuses of involved vehicles to 'Delivered'.
Approx. payload:

```
{
    "operation": "completeTransaction",
    "record": {
        "transaction_id": "00db8ed2-8117-49ab-807d-9b9d1db3a4f1"
    }
}
```

**Comment by k-tratseuski** [comment]
@AntonZakWork was done in [this issue](https://github.com/CarSnoop-Inc/carsnoop-issues/issues/29)
