### ISSUE TITLE
confirmPayment API should change transaction status

### ISSUE THREAD

**Issue by AntonZakWork** [CarSnoop-Inc/carsnoop-issues#73]
Successful call of currently available endpoint 'confirmPayment' should update status of transaction and involved vehicles to 'Shipping'

**Comment by jongilman8** [comment]
Done. @k-tratseuski - I had to make the following changes in databaseFunctions to get this to work, each change is attached in case the code gets overwritten:

1. New endpoint called confirmTransactionPayment
2. Updated the endpoint updatePayment
3. Updated the endpoint updateSubscription
4. Updated some logic in the main handler function
[confirmTransactionPayment.txt](https://github.com/CarSnoop-Inc/carsnoop-issues/files/10252241/confirmTransactionPayment.txt)
[updatePayment.txt](https://github.com/CarSnoop-Inc/carsnoop-issues/files/10252242/updatePayment.txt)
[session.txt](https://github.com/CarSnoop-Inc/carsnoop-issues/files/10252243/session.txt)
[updateSubscription.txt](https://github.com/CarSnoop-Inc/carsnoop-issues/files/10252244/updateSubscription.txt)
