### ISSUE TITLE
Driving license not saved

### ISSUE THREAD

**Issue by TonyaUkrainets** [CarSnoop-Inc/carsnoop-issues#79]
Driver's license uploaded with createContractDocument
![image](https://user-images.githubusercontent.com/112691890/208459916-a4dd668b-0e31-4c10-9daf-3acfce81e27e.png)

Driving license not saved. readTransaction doen`t return the Driver's license
![image](https://user-images.githubusercontent.com/112691890/208460082-8d307794-ac26-4548-8c80-7ea5b728be44.png)

**Comment by k-tratseuski** [comment]
@TonyaUkrainets done, ready for testing

**Comment by TonyaUkrainets** [comment]
fixed
