### ISSUE TITLE
API for payment confirmation (non-stripe flow)

### ISSUE THREAD

**Issue by AntonZakWork** [CarSnoop-Inc/carsnoop-issues#80]
Need separate endpoint for deals with non-stripe payment methods (cash, check etc.). Endpoint call should update database statuses the same way current confirmPayment does (status of transaction and involved vehicles changes to 'Shipping'), but payload shouldn`t contain stripe-specific information.
Approx. payload:
```
{
    "operation": "confirmNonStripePayment", // probably need some good name
    "record": {
        "transaction_id": "00db8ed2-8117-49ab-807d-9b9d1db3a4f1"
    }
} 
```

**Comment by k-tratseuski** [comment]
@AntonZakWork seems it's done in [issue](https://github.com/CarSnoop-Inc/carsnoop-issues/issues/73)

**Comment by k-tratseuski** [comment]
@billypilgrim88 we need to create a new endpoint or modify the current one `confirmTransactionPayment` to work now only with stripe payment method

**Comment by billypilgrim88** [comment]
I have updated the code for confirmPayment. If session_id (Stripe) is left blank, we only update the database:

{
    "operation": "confirmPayment",
    "record": {
        "session_id": "",
        "transaction_id": "37d787a8-89bf-4429-ae41-12c197991df4"
    }
}
