### ISSUE TITLE
Driver's licenses uploaded in profile are not transferred to contracts

### ISSUE THREAD

**Issue by TonyaUkrainets** [CarSnoop-Inc/carsnoop-issues#83]
Driver's licenses uploaded in profile
`readUser`
![image](https://user-images.githubusercontent.com/112691890/208721749-de0acef3-f23b-4d8f-86b3-7656a9c6223f.png)

Driver's licenses  are not transferred to contracts
`readTransaction`
![image](https://user-images.githubusercontent.com/112691890/208721904-b5904f11-c81c-473b-858c-4cba9fc9067b.png)

**Comment by TonyaUkrainets** [comment]
Same problem in reverse - If upload DL in contracts, then the DL is not displayed in the profile.
Same thing with deletion.

**Comment by k-tratseuski** [comment]
@TonyaUkrainets not reproducible
