### ISSUE TITLE
502 {"message": "Internal server error"} comes for request from Mobile

### ISSUE THREAD

**Issue by OlgaMalsteva** [CarSnoop-Inc/carsnoop-issues#85]
For request from Mobile: {"operation":"readVehicle","record":{"id":"a59a69dc-93e5-4747-a8b7-202ebc94707b"}}
502 {"message": "Internal server error"} error comes 
It should be fixed

**Comment by k-tratseuski** [comment]
@OlgaMalsteva done, ready for testing
