### ISSUE TITLE
Current subscription data 

### ISSUE THREAD

**Issue by Skalapendra69** [CarSnoop-Inc/carsnoop-issues#89]
We need an info about an account current subscription.
Could you add the info into `readAccount` response. I think it should be like
```
{
...
  "subscription" : {
      "name": "Free",
      "completedDeals": 1,
      "maxDealsOfCurrentSubscription": 1
       ...place for another data that can be needed...
   }
...
}
```

**Comment by k-tratseuski** [comment]
@Skalapendra69 done
We don't need `id` anymore, account will be retrieved from session
Example request body
```json
{
    "operation": "readAccount",
    "record": {}
}
```
Now this is a part of the response, for unlimited subscription `max_deals` is `null` (If have any suggestions, ping me)
```json
"subscription": {
        "name": "Free",
        "completed_deals": 0,
        "max_deals": 1
 }
```

**Comment by Skalapendra69** [comment]
So, we need an additional info.
```
"subscription": {
    "name": "Free",
    "completed_deals": 0,
    "max_deals": 1,
    "subscription_cost": 999.  // <------ this one
 }
```
![image](https://user-images.githubusercontent.com/50297089/209291361-ffd241df-f60d-49ae-a182-c35810d3bc79.png)

Regarding using null as infinity it's ok

**Comment by k-tratseuski** [comment]
@Skalapendra69 done,
```json
"subscription": {
    "name": "Free",
    "completed_deals": 0,
    "max_deals": 1,
    "price": 0
}
```
