### ISSUE TITLE
Need to add the "trade in" attribute to createShipment api

### ISSUE THREAD

**Issue by YunchytsK** [CarSnoop-Inc/carsnoop-issues#9]

**Comment by jongilman8** [comment]
Done, try this payload in createShipment:

{
    "operation": "createShipment",
    "record": {
        "transaction_id": "6ed1a429-f17f-4196-a53a-9850ca14e9d6",
        "pickup": {
            "street": "1233 N Hoyne Ave",
            "city": "Chicago",
            "state": "IL",
            "zip_code": "60622",
            "first_name": "Billy",
            "last_name": "Corgan",
            "phone": "312-567-8576",
            "business_name": "Howard Orloff Cadillac"
        },
        "dropoff": {
            "street": "480 W Poplar St",
            "city": "Zionsville",
            "state": "IN",
            "zip_code": "46077",
            "first_name": "Jon",
            "last_name": "Gilman",
            "phone": "317-370-9852",
            "business_name": ""
        },
        "vehicle": {
            "vin": "19UYA2250VL009163",
            "notes": "This is a test.",
            "mileage": 12310,
            "stock_number": "A1231"
        },
        "trade_in_vehicle": {
            "vin": "1G6AH5RXXG0121884",
            "notes": "This is a test.",
            "mileage": 123944,
            "stock_number": "0196"
        }
    }
}
