### ISSUE TITLE
Change the text of blocking errors

### ISSUE THREAD

**Issue by TonyaUkrainets** [CarSnoop-Inc/carsnoop-issues#90]
Primary blocking
Error should be "You’ve exceeded the number of attempts. Please try again in 60:00 min."

Permanent blocking
Error should be "You’ve exceeded the number of attempts. Please contact Support@carsnoop.com "

**Comment by TonyaUkrainets** [comment]
Need to change errors for registerUser and verifyEmail methods

**Comment by k-tratseuski** [comment]
@TonyaUkrainets done, ready for testing

**Comment by TonyaUkrainets** [comment]
fixed
