### ISSUE TITLE
Blocking on login flow does not work

### ISSUE THREAD

**Issue by TonyaUkrainets** [CarSnoop-Inc/carsnoop-issues#91]
Could you check please if the login flow blocking works?
At the moment, error does not come from the back-end after five unsuccessful attempts

**Comment by TonyaUkrainets** [comment]
The same problem with blocking after resending a new code.
![image](https://user-images.githubusercontent.com/112691890/209162975-7ad9fb17-3b01-4efb-a4d4-3b1ca5c481a9.png)

**Comment by k-tratseuski** [comment]
@TonyaUkrainets done, ready for testing

**Comment by TonyaUkrainets** [comment]
fixed
