### ISSUE TITLE
Question: How to get url for payment?

### ISSUE THREAD

**Issue by reutenkoivan** [CarSnoop-Inc/carsnoop-issues#92]
How can we get a URL:
* for the shipment payment?
* for the vehicle + shipment payment?

**Comment by reutenkoivan** [comment]
<img width="561" alt="image" src="https://user-images.githubusercontent.com/37533785/209520430-d67f4ae7-c207-4dbd-aa86-48c005abde57.png">

**Comment by reutenkoivan** [comment]
![Screenshot 2022-12-26 at 09 49 33](https://user-images.githubusercontent.com/37533785/209520649-a14fe78e-a4b7-4b77-8ce1-9ad801f4a5e0.png)

**Comment by billypilgrim88** [comment]
Use createPaymentCheckout

**Comment by billypilgrim88** [comment]
For payment + shipping, use a payload like this:

{
    "operation": "createPaymentCheckout",
    "record": {
        "transaction_id": "18b8c94c-441d-40ff-b573-94697655ed70",
        "success_url": "https://carsnoop.com",
        "cancel_url": "https://carsnoop.com",
        "items": [
            {
                "amount": 20000.00,
                "product_name": "Balance",
                "product_description": "Remaining Balance to Seller"
            },
            {
                "amount": 183.53,
                "product_name": "Shipping",
                "product_description": "Cost to Ship Vehicle"
            }
        ]
    }
}
