### ISSUE TITLE
Add stripe_patment_method info into readAccount response

### ISSUE THREAD

**Issue by Skalapendra69** [CarSnoop-Inc/carsnoop-issues#93]
We need an info if current account already has 'stripe account' and the payment method binded to it.

We need only a 'boolean' flag

For example 
```
{
  "has_payment_method": true/false
  ...
}
```

**Comment by k-tratseuski** [comment]
@Skalapendra69 done

**Comment by Skalapendra69** [comment]
So, here we go again. We need a separated API call to get an info if the user already has binded stripe paymentMethod.

Request example
```
{
  "operation": "checkStripePaymentMethod"
}
``` 

Response example
```
{
  "result": true/false
}
```

**Comment by k-tratseuski** [comment]
@Skalapendra69 done

**Comment by k-tratseuski** [comment]
@Skalapendra69 
```json
{
    "operation": "checkStripePaymentMethod",
    "record": {}
}
```
