### ISSUE TITLE
Invitation link is not working on mobile devices

### ISSUE THREAD

**Issue by OlgaMalsteva** [CarSnoop-Inc/carsnoop-issues#95]
Incorrect Invitation link work should be fixed
https://portal-dev.carsnoop.com/registration/invitation?email=kekir96324@irebah.com&accountId=c45111b9-101e-4272-a4e9-24765716f2be&verificationCode=6120
![image](https://user-images.githubusercontent.com/80024206/209654554-d57b3438-3cab-4ebb-a292-91483c770a7a.png)

**Comment by k-tratseuski** [comment]
@OlgaMalsteva fixed

**Comment by billypilgrim88** [comment]
S3 is not involved in this process, this appears to be a front end issue. The URL above is simply trying to access a front end page with URL variables being passed to the page. There is no S3.

**Comment by k-tratseuski** [comment]
@billypilgrim88 seems it's not related to the FE, check screenshot 1 (request from mobile device) and screenshot 2 (from browser). Seems s3 has some access settings based on header or smth like this

![image](https://user-images.githubusercontent.com/117080223/209683263-76dde4d2-9dd8-4a4c-89e6-8355a513ccbf.png)
![image](https://user-images.githubusercontent.com/117080223/209683283-11aeea25-9ed3-4408-8665-475fb38bd52f.png)

**Comment by billypilgrim88** [comment]
There is nothing on the S3 side that treats mobile requests differently from web requests. The issue must be on the front end side.

**Comment by k-tratseuski** [comment]
@billypilgrim88, we've noticed that the problem is in IPs. @OlgaMalsteva and I are from Belarus. So that's why we can't access the link, but other guys can. So maybe the problem is in CloudFront. What do u think, should we tackle that?

**Comment by k-tratseuski** [comment]
@OlgaMalsteva, we've decided to use VPN in such cases

**Comment by k-tratseuski** [comment]
Fixed
