### ISSUE TITLE
Wrong status for Vehicle in Shipment transaction

### ISSUE THREAD

**Issue by TonyaUkrainets** [CarSnoop-Inc/carsnoop-issues#96]
Transaction 37d787a8-89bf-4429-ae41-12c197991df4 in Shipping status
Vehicle 43793478-22e2-4f96-90ea-6eb943ce7d4a in Avaliable status

https://carsnoopworkspace.slack.com/archives/D048XEPGQ6Q/p1672219689710429

Add status check to confirmPayment

**Comment by k-tratseuski** [comment]
@TonyaUkrainets done, ready for testing

**Comment by TonyaUkrainets** [comment]
fixed
![image](https://user-images.githubusercontent.com/112691890/209991414-9866971a-c8d7-4c55-961a-117aeb7e8b84.png)
