### ISSUE TITLE
Caching in AWS

### ISSUE THREAD

**Issue by TonyaUkrainets** [CarSnoop-Inc/carsnoop-issues#97]
Not all changes are successfully delivered to the test environment, but there are no problems with builds. Clearing the cache on the client side does not help. 
Is caching performed on the AWS side and is it possible to disable it?

**Comment by Skalapendra69** [comment]
It looks like when new build is deployed AWS returns not new index.html but cached one (created by previous build). So we get index.html with old dependencies (.js, .css) on `https://portal-dev.carsnoop.com/`. Is it possible to perform kind of force cache invalidation when new index.html is uploaded into folder?

**Comment by billypilgrim88** [comment]
Done, in the future, those with AWS credentials can follow these 4 steps to clear the CloudFront cache:

https://tecadmin.net/remove-cloudfront-cache/
