### ISSUE TITLE
resetPassword is case sensitive

### ISSUE THREAD

**Issue by TonyaUkrainets** [CarSnoop-Inc/carsnoop-issues#99]
Example: Xicac29726@miarr.com

All methods that are used during registration and login are case insensitive, except for **resetPassword**
![image](https://user-images.githubusercontent.com/112691890/209845567-7918441b-85c0-4f1f-a5d3-7ace19a61299.png)

**Comment by k-tratseuski** [comment]
@TonyaUkrainets done, ready for testing

**Comment by TonyaUkrainets** [comment]
fixed
